### ISSUE TITLE
Error when you deploy phtyon-client to production google cloud enviroment .

### ISSUE THREAD

**Issue by tsujimasato** [GoogleCloudPlatform/python-docs-samples#1072]
## In which file did you encounter the issue?
I was using GAE(python standard environment.) and encountered this error.
This is maybe because GAE does not allow us to use multiprocessing although it worked well in development.
I tried "try except" the "import multiprocessing "  so that I can skip that but it courses other Error.
Do you have any idea to avoid these error? Do I have to use REST API instead of python client.

### Did you change the file? If so, how?
No

## Describe the issue

cannot import name _args_from_interpreter_flags (/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:1528)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/webapp/mail_handlers.py", line 70, in post
    self.receive(mail.InboundEmailMessage(self.request.body))
  File "/base/data/home/apps/b~mierusuden/20170815t221226.403405559975627211/handle_incoming_email.py", line 37, in receive
    attachment  = transcribe_file(filename, data)
  File "/base/data/home/apps/b~mierusuden/20170815t221226.403405559975627211/speech.py", line 59, in transcribe_file
    from google.cloud import speech
  File "/base/data/home/apps/b~mierusuden/20170815t221226.403405559975627211/lib/google/cloud/speech/__init__.py", line 22, in <module>
    from google.cloud.speech.client import Client
  File "/base/data/home/apps/b~mierusuden/20170815t221226.403405559975627211/lib/google/cloud/speech/client.py", line 25, in <module>
    from google.cloud.speech._gax import GAPICSpeechAPI
  File "/base/data/home/apps/b~mierusuden/20170815t221226.403405559975627211/lib/google/cloud/speech/_gax.py", line 17, in <module>
    from google.cloud.gapic.speech.v1.speech_client import SpeechClient
  File "/base/data/home/apps/b~mierusuden/20170815t221226.403405559975627211/lib/google/cloud/gapic/speech/v1/speech_client.py", line 31, in <module>
    from google.gapic.longrunning import operations_client
  File "/base/data/home/apps/b~mierusuden/20170815t221226.403405559975627211/lib/google/gapic/longrunning/operations_client.py", line 45, in <module>
    from google.gax import api_callable
  File "/base/data/home/apps/b~mierusuden/20170815t221226.403405559975627211/lib/google/gax/__init__.py", line 36, in <module>
    import multiprocessing as mp
  File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/multiprocessing/__init__.py", line 65, in <module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/multiprocessing/util.py", line 41, in <module>
    from subprocess import _args_from_interpreter_flags
ImportError: cannot import name _args_from_interpreter_flags

**Comment by jonparrott** [comment]
Unfortunately, App Engine standard does not support these client libraries yet. We are working on it and you can follow https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1893#issuecomment-322512490 for updates and more details.

**Comment by tsujimasato** [comment]
I got it. Sorry for the duplicate question.

**Comment by jonparrott** [comment]
No worries. :)
