### ISSUE TITLE
Web server fails to launch

### ISSUE THREAD

**Issue by hotoku** [GoogleCloudPlatform/python-docs-samples#10732]
## In which file did you encounter the issue?

/run/idp-sql/requirements.txt

## Did you change the file? If so, how?

no.

## Describe the issue

**description**
`run/idp-sql/main.py` provides a web server made of Flask. But this server fails to launch.

The cause is that the given `requirements.txt` will install Flask 2.1.0 and Werkzeug 3.0.0.
But Flask 2.1.0 does not work with Werkzeug 3.0.0.

cf: https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls
 
**how to reproduce**

```shell
cd run/idp-sql
pip install -r requirements.txt
gunicorn --bind :18888 --workers 1 --threads 8 --timeout 0 main:app
```

**error message**

```shell
[2023-10-05 08:09:07 +0900] [16101] [INFO] Starting gunicorn 20.1.0
[2023-10-05 08:09:07 +0900] [16101] [INFO] Listening at: http://0.0.0.0:18888 (16101)
[2023-10-05 08:09:07 +0900] [16101] [INFO] Using worker: gthread
[2023-10-05 08:09:07 +0900] [16150] [INFO] Booting worker with pid: 16150
[2023-10-05 08:09:07 +0900] [16150] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/hotoku/projects/inctore/predapi/python-docs-samples/run/idp-sql/main.py", line 20, in <module>
    from flask import Flask, render_template, request, Response
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/flask/app.py", line 27, in <module>
    from . import cli
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/flask/cli.py", line 17, in <module>
    from .helpers import get_debug_flag
  File "/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/Users/hotoku/.anyenv/envs/pyenv/versions/3.11.4/envs/idp-sql/lib/python3.11/site-packages/werkzeug/urls.py)
[2023-10-05 08:09:07 +0900] [16150] [INFO] Worker exiting (pid: 16150)
[2023-10-05 08:09:07 +0900] [16101] [INFO] Shutting down: Master
[2023-10-05 08:09:07 +0900] [16101] [INFO] Reason: Worker failed to boot.
```

**Comment by glasnt** [comment]
This has been fixed in #10727
