### ISSUE TITLE
Speech API examples can't install in python 2.7.6 and 3.4.2

### ISSUE THREAD

**Issue by mei-li** [GoogleCloudPlatform/python-docs-samples#1106]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/README.rst
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/requirements.txt

### Did you change the file? If so, how?
No

## Describe the issue

I just tried to install the requirements, for both Python 2.7.6 and Python 3.4.2 and it failed. It worked for 3.5.1, so I think the documentation has to be updated.

**Python 2.7 error**
```
$ pip install -r requirements.txt 
Downloading/unpacking google-cloud-speech==0.29.0 (from -r requirements.txt (line 1))
  Downloading google-cloud-speech-0.29.0.tar.gz (137kB): 137kB downloaded
  Running setup.py egg_info for package google-cloud-speech
    
    warning: no files found matching '*.proto' under directory 'google'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
Downloading/unpacking google-cloud-core>=0.27.0,<0.28dev (from google-cloud-speech==0.29.0->-r requirements.txt (line 1))
  Downloading google-cloud-core-0.27.1.tar.gz (58kB): 58kB downloaded
  Running setup.py egg_info for package google-cloud-core
    error in google-cloud-core setup command: Invalid environment marker: python_version<"3.2"
    Complete output from command python setup.py egg_info:
    error in google-cloud-core setup command: Invalid environment marker: python_version<"3.2"

----------------------------------------
Cleaning up...

```

**Python 3.4 error**
```Installing collected packages: google-cloud-speech, google-gax, googleapis-common-protos, google-cloud-core, dill, future, grpcio, google-auth, ply, protobuf, requests, six, setuptools, pyasn1, cachetools, pyasn1-modules, rsa, certifi, chardet, idna, urllib3
  Running setup.py install for google-gax
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extension import Extension
      File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/setuptools/dist.py", line 16, in <module>
        import pkg_resources
      File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 2717, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 682, in subscribe
        callback(dist)
      File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 2717, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 2255, in activate
        list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))
      File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 1851, in declare_namespace
        path = sys.modules[parent].__path__
    KeyError: 'google.cloud'
    Complete output from command /home/meili/.pyenv/versions/speechp3/bin/python3.4 -c "import setuptools, tokenize;__file__='/home/meili/.pyenv/versions/speechp3/build/google-gax/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zbwnuk02-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/meili/.pyenv/versions/speechp3/include/site/python3.4:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/setuptools/__init__.py", line 11, in <module>

    from setuptools.extension import Extension

  File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/setuptools/extension.py", line 5, in <module>

    from setuptools.dist import _get_unpatched

  File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/setuptools/dist.py", line 16, in <module>

    import pkg_resources

  File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 2717, in <module>

    add_activation_listener(lambda dist: dist.activate())

  File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 682, in subscribe

    callback(dist)

  File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 2717, in <lambda>

    add_activation_listener(lambda dist: dist.activate())

  File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 2255, in activate

    list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))

  File "/home/meili/.pyenv/versions/speechp3/lib/python3.4/site-packages/pkg_resources.py", line 1851, in declare_namespace

    path = sys.modules[parent].__path__

KeyError: 'google.cloud'

----------------------------------------
Cleaning up...
Command /home/meili/.pyenv/versions/speechp3/bin/python3.4 -c "import setuptools, tokenize;__file__='/home/meili/.pyenv/versions/speechp3/build/google-gax/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zbwnuk02-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/meili/.pyenv/versions/speechp3/include/site/python3.4 failed with error code 1 in /home/meili/.pyenv/versions/speechp3/build/google-gax
Storing debug log for failure in /home/meili/.pip/pip.log
```

**Comment by jonparrott** [comment]
Hi @mei-li! For the Python 2.7 issue, you just need to make sure you have the latest versions of pip and setuptools installed.

We don't support 3.4, the minimum version is 3.5.

**Comment by mei-li** [comment]
In the [README](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/README.rst)  it says `Samples are compatible with Python 2.7 and 3.4+.` Which sounds like 3.4 is supported

**Comment by jonparrott** [comment]
@mei-li good catch. I may need to update those. The libraries may work in 3.4 - that issue could be a side effect of outdating pip & setuptools in your 3.4 installation.

**Comment by mei-li** [comment]
@jonparrott After updating pip to `pip 9.0.1` the problem persists,in 3.4. Btw in 2.7 was resolved, thanks for the hint.
