### ISSUE TITLE
Generative AI Sample - evaluate_model.py example is failing pytest

### ISSUE THREAD

**Issue by msampathkumar** [GoogleCloudPlatform/python-docs-samples#11264]
Following the pytest results for `evaluate_model_test.py`

```
$ pytest evaluate_model_test.py 
============================================================ test session starts ============================================================
platform darwin -- Python 3.9.12, pytest-6.2.4, py-1.11.0, pluggy-0.13.1 -- python-docs-samples/env/bin/python3
cachedir: .pytest_cache
rootdir: python-docs-samples, configfile: pytest.ini
plugins: flaky-3.7.0, xdist-3.3.1
collected 1 item                                                                                                                            

evaluate_model_test.py::test_evaluate_model FAILED                                                                                    [100%]

================================================================= FAILURES ==================================================================
____________________________________________________________ test_evaluate_model ____________________________________________________________
Traceback (most recent call last):
  File "python-docs-samples/generative_ai/evaluate_model_test.py", line 29, in test_evaluate_model
    eval_metrics = evaluate_model.evaluate_model(
  File "python-docs-samples/generative_ai/evaluate_model.py", line 49, in evaluate_model
    eval_metrics = model.evaluate(task_spec=task_spec)
  File "python-docs-samples/env/lib/python3.9/site-packages/vertexai/language_models/_evaluatable_language_models.py", line 660, in evaluate
    pipeline_job = aiplatform.PipelineJob(
  File "python-docs-samples/env/lib/python3.9/site-packages/google/cloud/aiplatform/pipeline_jobs.py", line 218, in __init__
    pipeline_json = yaml_utils.load_yaml(
  File "python-docs-samples/env/lib/python3.9/site-packages/google/cloud/aiplatform/utils/yaml_utils.py", line 56, in load_yaml
    return _load_yaml_from_https_uri(path, credentials)
  File "python-docs-samples/env/lib/python3.9/site-packages/google/cloud/aiplatform/utils/yaml_utils.py", line 143, in _load_yaml_from_https_uri
    response = request.urlopen(req)
  File ".pyenv/versions/3.9.12/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File ".pyenv/versions/3.9.12/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File ".pyenv/versions/3.9.12/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File ".pyenv/versions/3.9.12/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File ".pyenv/versions/3.9.12/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File ".pyenv/versions/3.9.12/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
========================================================== short test summary info ==========================================================
FAILED evaluate_model_test.py::test_evaluate_model - urllib.error.HTTPError: HTTP Error 404: Not Found
============================================================ 1 failed in 14.83s =============================================================
$

```

**Comment by jsondai** [comment]
The latest pipeline templates were not correctly labeled. This is now resolved.

**Comment by iennae** [comment]
Thanks @jsondai
