### ISSUE TITLE
Can't transcribe a file...

### ISSUE THREAD

**Issue by mol3earth** [GoogleCloudPlatform/python-docs-samples#1163]
## In which file did you encounter the issue?

/python-docs-samples/speech/cloud-client/transcribe_async.py

### Did you change the file? If so, how?

Nope

## Describe the issue

not sure

```
python transcribe_async.py gs://agi_audio/01_Overview_Audio.mp3

Traceback (most recent call last):                                                                                                                                                                 
  File "transcribe_async.py", line 96, in <module>                                                                                                                                                   
    transcribe_gcs(args.path)                                                                                                                                                                      
  File "transcribe_async.py", line 76, in transcribe_gcs                                                                                                                                                     
    operation = client.long_running_recognize(config, audio)                                                                                                                                       
  File "[PATH_TO_VENV]/local/lib/python2.7/site-packages/google/cloud/gapic/speech/v1/speech_client.py", line 250, in long_running_recognize                                           
    options), self.operations_client,                                                                                                                                                              
  File "[PATH_TO_VENV]/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 452, in inner                                                                               
    return api_caller(api_call, this_settings, request)                                                                                                                                            
  File "[PATH_TO_VENV]/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)                                                                                                                                                                         
  File "[PATH_TO_VENV]/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 380, in inner                                                                               
    gax.errors.create_error('RPC failed', cause=exception))                                                                                                                                        
  File "[PATH_TO_VENV]/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 376, in inner                                                                               
    return a_func(*args, **kwargs)                                                                                                                                                                 
  File "[PATH_TO_VENV]/local/lib/python2.7/site-packages/google/gax/retry.py", line 68, in inner                                                                                       
    return a_func(*updated_args, **kwargs)                                                                                                                                                         
  File "[PATH_TO_VENV]/local/lib/python2.7/site-packages/grpc/_channel.py", line 507, in __call__                                                                                      
    return _end_unary_response_blocking(state, call, False, deadline)                                                                                                                              
  File "[PATH_TO_VENV]/local/lib/python2.7/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)                                                                                                                                               
google.gax.errors.GaxError: GaxError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>) 
```

**Comment by jonparrott** [comment]
@jerjou @gguuss can one of you take a look?

**Comment by jerjou** [comment]
* The API [does not support mp3](https://cloud.google.com/speech/reference/rest/v1/RecognitionConfig#AudioEncoding) - try transcoding to a WAV file, or FLAC, and try again (making sure to update the `transcribe_async.py` sample to specify the format it's in)
* How long is the audio file?
* How long did it take before you got that error?

**Comment by mol3earth** [comment]
thanks @jerjou I wasn't aware of the mp3 limitation.

my audio file was about 35 seconds long. 

It took a bit. maybe a minute or so. 

alas, I get the same error with even 
`python transcribe_async.py resources/audio.raw`

so i don't think it is my file that is the only problem.

**Comment by jerjou** [comment]
Hm... has this worked for you in the past? It looks like `DEADLINE_EXCEEDED` could be an error the client throws (eg if it's having trouble connecting to the server). Does it work with `transcribe.py`, for instance? Or do any of the other samples in this repo work for you? Is there anything special about your network, or your python environment (or your grpc environment)? Any detail about the environment you're running this in that might be unusual would be helpful. For starters - what OS are you running this under? Are you behind a firewall or anything?

**Comment by mol3earth** [comment]
I am on windows 10 using the Ubuntu built in. 
I am behind a firewall, but I haven't had an issue with connecting to google before this.

i ended up abandoning this github project and i just construct it from scratch now using requests and an api key.

**Comment by jerjou** [comment]
Fair enough. If using `requests` works, then I'd hypothesize an issue with grpc and/or http/2 interacting with your firewall (assuming this is the first API you've hit via GRPC, instad of REST). Anyway, it sounds like you've moved on, which is fine. The REST endpoint should work fine for non-streaming transcription.

Also FYI - if you'd like to use a service account for auth instead of an api key, I'd suggest taking a look at the [google-auth](https://google-auth.readthedocs.io/en/latest/user-guide.html#requests) package.
