### ISSUE TITLE
RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with StatusCode.UNAUTHENTICATED

### ISSUE THREAD

**Issue by pankajkumar** [GoogleCloudPlatform/python-docs-samples#1165]
I am trying to connect to google vision API for document to text conversion when encountered this error. 

Here is the stacktrace:- 

```
File "/usr/local/lib/python2.7/site-packages/google/cloud/gapic/vision/v1/image_annotator_client.py", line 179, in batch_annotate_images
    return self._batch_annotate_images(request, options)
  File "/usr/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "/usr/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.UNAUTHENTICATED, Getting metadata from plugin failed with error: Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi", line 138, in grpc._cython.cygrpc.plugin_get_metadata (src/python/grpcio/grpc/_cython/cygrpc.c:7075)
  File "/usr/local/lib/python2.7/site-packages/grpc/_plugin_wrapping.py", line 91, in __call__
    AuthMetadataPluginCallback(wrapped_cygrpc_callback))
  File "/usr/local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 73, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/usr/local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 61, in _get_authorization_headers
    headers)
  File "/usr/local/lib/python2.7/site-packages/google/auth/credentials.py", line 121, in before_request
    self.refresh(request)
  File "/usr/local/lib/python2.7/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/usr/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 143, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 104, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/usr/local/lib/python2.7/site-packages/google/auth/transport/requests.py", line 115, in __call__
    raise exceptions.TransportError(exc)
TransportError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)
```

And here is dump of my pip freeze, I am using google-auth version 1.1.1:- 

```
aniso8601==1.3.0
appdirs==1.4.3
asn1crypto==0.22.0
boto3==1.4.4
botocore==1.5.77
cachetools==2.0.1
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.4
click==6.7
conda==4.3.16
cryptography==1.9
dill==0.2.7.1
Django==1.11.1
djangorestframework==3.6.3
docutils==0.13.1
enum34==1.1.6
Flask==0.12.2
Flask-Cors==3.0.3
Flask-RESTful==0.3.6
future==0.16.0
futures==3.1.1
fuzzywuzzy==0.15.1
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gapic-google-cloud-pubsub-v1==0.15.4
gapic-google-cloud-spanner-admin-database-v1==0.15.3
gapic-google-cloud-spanner-admin-instance-v1==0.15.3
gapic-google-cloud-spanner-v1==0.15.3
google-auth==1.1.1
google-cloud==0.27.0
google-cloud-bigquery==0.26.0
google-cloud-bigtable==0.26.0
google-cloud-core==0.26.0
google-cloud-datastore==1.2.0
google-cloud-dns==0.26.0
google-cloud-error-reporting==0.26.0
google-cloud-language==0.27.0
google-cloud-logging==1.2.0
google-cloud-monitoring==0.26.0
google-cloud-pubsub==0.27.0
google-cloud-resource-manager==0.26.0
google-cloud-runtimeconfig==0.26.0
google-cloud-spanner==0.26.0
google-cloud-speech==0.28.0
google-cloud-storage==1.3.2
google-cloud-translate==1.1.0
google-cloud-videointelligence==0.25.0
google-cloud-vision==0.26.0
google-gax==0.15.15
google-resumable-media==0.2.3
googleapis-common-protos==1.5.3
grpc-google-iam-v1==0.11.4
grpcio==1.6.3
httplib2==0.10.3
idna==2.5
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
MarkupSafe==1.0
monotonic==1.3
MultipartPostHandler==0.1.0
numpy==1.13.1
oauth2client==3.0.0
olefile==0.44
opencv-python==3.3.0.10
packaging==16.8
pandas==0.20.3
pdfminer==20140328
Pillow==4.3.0
ply==3.8
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
proto-google-cloud-pubsub-v1==0.15.4
proto-google-cloud-spanner-admin-database-v1==0.15.3
proto-google-cloud-spanner-admin-instance-v1==0.15.3
proto-google-cloud-spanner-v1==0.15.3
protobuf==3.4.0
pyasn1==0.3.7
pyasn1-modules==0.1.5
pycosat==0.6.1
pycparser==2.17
pymongo==3.4.0
pyodbc==4.0.17
pyOpenSSL==17.0.0
pyparsing==2.2.0
pysolr==3.6.0
python-dateutil==2.6.0
python-Levenshtein==0.12.0
pytz==2017.2
requests==2.18.1
rsa==3.4.2
ruamel.ordereddict==0.4.13
ruamel.yaml==0.15.34
s3transfer==0.1.10
schedule==0.4.3
six==1.10.0
tenacity==4.4.0
urllib3==1.21.1
virtualenv==15.1.0
watson-developer-cloud==0.26.0
Werkzeug==0.12.2
```

Any help would be appreciated.

**Comment by engelke** [comment]
The libraries involved have been updated many times since this report, and the sample regularly passes tests in both Python 2.7 and 3.7.
