### ISSUE TITLE
Trouble accessing analyze_entity_sentiment method

### ISSUE THREAD

**Issue by valmunos** [GoogleCloudPlatform/python-docs-samples#1171]
## In which file did you encounter the issue?

C:\Users\Vincent\Desktop\NLP\env\lib\site-packages\google\cloud\exceptions.py

### Did you change the file? If so, how?

No files have been changed.

## Describe the issue

I will try to be as brief as possible.  I have a script where I am first translating text from Dutch to English using the translation API and then passing the result of that translation to the natural language API for sentiment analysis.  Today, I decided to try the new entity sentiment analysis feature using the example code that is found in the documentation.  Unfortunately this is resulting in the follwing AttributeError:

Traceback (most recent call last):
  File "translate.py", line 104, in <module>
    entities_text(english_text)
  File "translate.py", line 79, in entities_text
    result = client.analyze_entity_sentiment(document, encoding)
AttributeError: 'LanguageServiceClient' object has no attribute 'analyze_entity_sentiment'

I did some digging around and realized this was likely related to the feature having only been released a month ago.  Naturally, I pip upgraded the google-cloud-language library to version 0.29.0 to see if that might solve my problem.  Unfortunately, when running the same script again I ran into yet another error, this time a ModuleNotFoundError:

Traceback (most recent call last):
  File "translate.py", line 4, in <module>
    from google.cloud import translate
  File "C:\Users\Vincent\Desktop\NLP\env\lib\site-packages\google\cloud\translate.py", line 18, in <module>
    from google.cloud.translate_v2 import __version__
  File "C:\Users\Vincent\Desktop\NLP\env\lib\site-packages\google\cloud\translate_v2\__init__.py", line 21, in <module>
    from google.cloud.translate_v2.client import Client
  File "C:\Users\Vincent\Desktop\NLP\env\lib\site-packages\google\cloud\translate_v2\client.py", line 23, in <module>
    from google.cloud.translate_v2._http import Connection
  File "C:\Users\Vincent\Desktop\NLP\env\lib\site-packages\google\cloud\translate_v2\_http.py", line 17, in <module>
    from google.cloud import _http
  File "C:\Users\Vincent\Desktop\NLP\env\lib\site-packages\google\cloud\_http.py", line 23, in <module>
    from google.cloud import exceptions
  File "C:\Users\Vincent\Desktop\NLP\env\lib\site-packages\google\cloud\exceptions.py", line 24, in <module>
    from google.api.core import exceptions
ModuleNotFoundError: No module named 'google.api.core'

My next thought was to pip upgrade google-cloud-core to a new version but this has not resolved anything.  I am not a pip wizard by any means so some help would be very much appreciated.

Thanks!

**Comment by jonparrott** [comment]
/cc @lukesneeringer

@valmunos can you tell us the output of `pip freeze`?

**Comment by engelke** [comment]
This problem happened a while ago, and the client libraries should be up to date now. The tests have been passing regularly.
