### ISSUE TITLE
Video that are not demo are not working Video Intelligence API

### ISSUE THREAD

**Issue by yelena-audiencescience** [GoogleCloudPlatform/python-docs-samples#1175]
## In which file did you encounter the issue?

python-docs-samples/video/cloud-client/labels/labels.py
### Did you change the file? If so, how?
I did not change the file. 

## Describe the issue
Essentially when I run python labels.py gs://demomaker/gbikes_dinosaur.mp4 or
python labels.py gs://demomaker/cats
it works but when I try my own video (a 3-4 minute video from youtube) it doesn't work.
I also tried a shorter video that was 10 seconds long and it didn't work. I haven't been able to get it to work on non-demo videos. 

This is the error I get:

Traceback (most recent call last):

  File "<ipython-input-3-23def0c02183>", line 3, in <module>
    operation = video_client.annotate_video(path, features)

  File "C:\Users\kernogiy\AppData\Local\Continuum\Anaconda3\Lib\site-packages\google\cloud\videointelligence_v1beta2\gapic\video_intelligence_service_client.py", line 224, in annotate_video
    self._annotate_video(request, options), self.operations_client,

  File "C:\Users\kernogiy\AppData\Local\Continuum\Anaconda3\Lib\site-packages\google\gax\api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)

  File "C:\Users\kernogiy\AppData\Local\Continuum\Anaconda3\Lib\site-packages\google\gax\api_callable.py", line 438, in base_caller
    return api_call(*args)

  File "C:\Users\kernogiy\AppData\Local\Continuum\Anaconda3\Lib\site-packages\google\gax\api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)

  File "C:\Users\kernogiy\AppData\Local\Continuum\Anaconda3\Lib\site-packages\google\gax\retry.py", line 127, in inner
    ' classified as transient', exception)

RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Request contains an invalid argument.)>)

**Comment by jonparrott** [comment]
@dizcology can you take a look?

**Comment by gguuss** [comment]
1080p MP4 / MOV, H.264 with MPEG audio seems to do the trick for me. What is the format of your video file?

**Comment by engelke** [comment]
This may be an issue with the underlying API, and not the sample code. Please use the tracker at https://cloud.google.com/support/docs/issue-trackers for this.
