### ISSUE TITLE
ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL

### ISSUE THREAD

**Issue by titusece** [GoogleCloudPlatform/python-docs-samples#1284]
## In which file did you encounter the issue?

/python-docs-samples/speech/cloud-client/transcribe_streaming_mic.py

### Did you change the file? If so, how?

Nope.

## Describe the issue

Getting the following errors while executing '**transcribe_streaming_mic.py**' python example.

I have exported the 'GOOGLE_APPLICATION_CREDENTIALS' for KEY location.
Can you please help me on this issue ?

```
(env) root@linux:/python-docs-samples/speech/cloud-client# 
(env) root@linux:/python-docs-samples/speech/cloud-client# python transcribe_streaming_mic.py
E1031 16:56:06.657955430    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:06.740789555    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:06.815913513    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:06.968742346    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:07.094688971    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:07.174502180    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:07.277684055    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:07.378768763    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:07.532342763    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:07.676538846    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:07.791226930    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:07.909150763    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:08.005649888    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:08.248604888    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:08.347812180    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:08.535098430    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1031 16:56:08.724522555    2913 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Traceback (most recent call last):
  File "transcribe_streaming_mic.py", line 193, in <module>
    main()
  File "transcribe_streaming_mic.py", line 189, in main
    listen_print_loop(responses)
  File "transcribe_streaming_mic.py", line 128, in listen_print_loop
    for response in responses:
  File "/env/lib/python2.7/site-packages/grpc/_channel.py", line 348, in next
    return self._next()
  File "/env/lib/python2.7/site-packages/grpc/_channel.py", line 339, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
(env) root@linux:/python-docs-samples/speech/cloud-client# 
(env) root@linux:/python-docs-samples/speech/cloud-client# 
(env) root@linux:/python-docs-samples/speech/cloud-client# 
```

**Comment by jonparrott** [comment]
@titusece can you let us know your Python version? SSL verification failing is indicative of older Pythons that lack SNI support.

**Comment by titusece** [comment]
Hi,
Thanks for your reply.
As far as I remember that it worked for my friend with the same setup.
python version is 2.7.

**Comment by jonparrott** [comment]
It's almost certainly due to older SSL. I would highly suggest installing `requests[security]` and upgrading your Python version.

**Comment by tab1293** [comment]
@jonparrott I have tested with python 2.7.15 with `request[security]` installed and still seeing this issue.

**Comment by jonparrott** [comment]
Try this workaround: https://github.com/lightningnetwork/lnd/issues/795#issuecomment-374903140

This actually seems to be a bug in grpc. @nathanielmanistaatgoogle @mehrdada

**Comment by tab1293** [comment]
@jonparrott even with that work around, still not working.

```
$ python --version
Python 2.7.15

$ python -c "import ssl; print ssl.OPENSSL_VERSION"
OpenSSL 1.0.2o  27 Mar 2018
```

Is there any additional information I can include to help debug?

**Comment by jonparrott** [comment]
Your gRPC version and OS will be helpful

**Comment by tab1293** [comment]
Python's gRPC version is at 1.9.1 and I'm on MacOS 10.13

**Comment by nathanielmanistaatgoogle** [comment]
@jiangtaoli2016, @jboeuf: what might cause this user to see `E0503 12:02:25.491373000 140735530255168 ssl_transport_security.cc:1063] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`?

**Comment by jonparrott** [comment]
Filed https://github.com/grpc/grpc/issues/15261 to track this.

**Comment by nathanielmanistaatgoogle** [comment]
@jonparrott: great; see you [there](https://github.com/grpc/grpc/issues/15261).

**Comment by aman-merkle** [comment]
Did you find any solution?
