### ISSUE TITLE
Running a query.py with destination_table argument results in an error

### ISSUE THREAD

**Issue by quarrazzella** [GoogleCloudPlatform/python-docs-samples#1291]
## In which file did you encounter the issue?

query.py - https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/query.py

### Did you change the file? If so, how?

No, I didn't change a thing.

## Describe the issue

I'm trying to execute it with the "--destination_table" argument. This here's the command

```
$ python query.py --destination_table my_dataset.my_test_table '#standardSQL
SELECT sessionId FROM `project.dataset.table` LIMIT 10'
```

Here's what I get:

_Traceback (most recent call last):
  File "query.py", line 74, in <module>
    query_destination_table(args.query, dataset, table)
  File "query.py", line 31, in query_destination_table
    query_job = client.run_async_query(str(uuid.uuid4()), query)
AttributeError: 'Client' object has no attribute 'run_async_query'_

**Comment by tswast** [comment]
I don't see `run_async_query` in https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/query.py. Are you sure you have downloaded the latest version of the sample program?
