### ISSUE TITLE
[generative_ai]: Translation "with LLM" samples are not working anymore.

### ISSUE THREAD

**Issue by Valeriy-Burlaka** [GoogleCloudPlatform/python-docs-samples#12997]
## In which file did you encounter the issue?

**N/A** — The samples in issue are written as **Markdown**. I worked on replacing them with actual Python samples.

## Did you change the file? If so, how?

No.

## Describe the issue

Both "Translation LLM" samples no longer work ([1](https://cloud.google.com/vertex-ai/generative-ai/docs/translate/translate-text#zero_shot_translation-python), [2](https://cloud.google.com/vertex-ai/generative-ai/docs/translate/translate-text#zero_shot_translation-python)), failing to create the `aiplatform` endpoint with `cloud-translate-text` LLM given in the example:

```python
from google.cloud import aiplatform

endpoint = aiplatform.Endpoint('projects/PROJECT_ID/locations/LOCATION/publishers/google/models/cloud-translate-text')
...
```

Error:

```
Traceback (most recent call last):
  File "/Users/valeriiburlaka/Projects/Google-Vertex/Repositories/vertex-gemini-samples/samples/pages/translation/translate_llm.py", line 26, in <module>
    translate()
  File "/Users/valeriiburlaka/Projects/Google-Vertex/Repositories/vertex-gemini-samples/samples/pages/translation/translate_llm.py", line 12, in translate
    endpoint = aiplatform.Endpoint(endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valeriiburlaka/Projects/Google-Vertex/Repositories/vertex-gemini-samples/.venv/lib/python3.12/site-packages/google/cloud/aiplatform/models.py", line 664, in __init__
    endpoint_name = utils.full_resource_name(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valeriiburlaka/Projects/Google-Vertex/Repositories/vertex-gemini-samples/.venv/lib/python3.12/site-packages/google/cloud/aiplatform/utils/__init__.py", line 221, in full_resource_name
    resource_id_validator(resource_name)
  File "/Users/valeriiburlaka/Projects/Google-Vertex/Repositories/vertex-gemini-samples/.venv/lib/python3.12/site-packages/google/cloud/aiplatform/utils/__init__.py", line 157, in validate_id
    raise ValueError(f"Resource {resource_id} is not a valid resource id.")
ValueError: Resource projects/fluxon-vertex-cookbook/locations/us-central1/publishers/google/models/cloud-translate-text is not a valid resource id.
```

**Comment by glasnt** [comment]
Can you please provide your `pip list` to understand which packages you're using, to identify if that is related? Thank you in advance.

**Comment by Valeriy-Burlaka** [comment]
@glasnt, thank you for checking this out! — I updated the issue with my environment info.
 
I just noticed that the "Translate text" guide [page](https://cloud.google.com/vertex-ai/generative-ai/docs/translate/translate-text), which hosted these samples, has changed completely and isn't listing _any_ code samples anymore. Is this expected?

Thanks!

**Comment by Aaditya-git** [comment]
Is anyone working on it? I want to give it a try.
