### ISSUE TITLE
Restrictions to input video format? --Getting Error

### ISSUE THREAD

**Issue by borisbolvig** [GoogleCloudPlatform/python-docs-samples#1315]
without modification running
python-docs-samples/video/cloud-client/analyze/analyze.py

I am attempting to run label detection on a local video file.
It seems not to work for certain widescreen aspect ratios.

I am getting valid response for the demo files and other examples, but for .mov movie trailers as found on http://www.hd-trailers.net/ it doesn't work. 
Specific example http://movietrailers.apple.com/movies/sony_pictures/all-the-money-in-the-world/all-the-money-in-the-world-trailer-2_h480p.mov

Error message is not helpful:
`python analyze.py labels_file all-the-money-in-the-world-trailer-2_h480p.mov`

Traceback (most recent call last):
  File "analyze.py", line 301, in <module>
    analyze_labels_file(args.path)
  File "analyze.py", line 190, in analyze_labels_file
    features=features, input_content=input_content)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/videointelligence_v1/gapic/video_intelligence_service_client.py", line 202, in annotate_video
    operation = self._annotate_video(request, retry=retry, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/gapic_v1/method.py", line 134, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/grpc_helpers.py", line 54, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/home/boris/.local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.

There don't seem to be any explicit restrictions on the video file input in the documentation, so can anyone elaborate on the issue?

Thanks.

**Comment by jonparrott** [comment]
@dizcology can you take a look?

**Comment by borisbolvig** [comment]
#1175 possibly related

**Comment by gguuss** [comment]
In my experience, the best format for the video API is:

* 1080p MP4 / MOV, H.264 with MPEG audio

**Comment by engelke** [comment]
This may be an issue with the underlying API, and not the sample code. Please use the tracker at https://cloud.google.com/support/docs/issue-trackers for this.
