### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by Osiris1975** [GoogleCloudPlatform/python-docs-samples#1363]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/cloud-client/quickstart.py

### Did you change the file? If so, how?

Yes, I changed the value of the string bucket_name to 'amr-test-bucket'

## Describe the issue

When I try to run this quickstart script for creating a bucket using the cloud storage API from the PyCharm IDE using a run configuration, I get the error below pasted below.

However, if I run the same commands in a REPL/Python console, it works fine. 

Stack Trace:

```
"D:\Miniconda3\envs\Python-2.7 Web\python.exe" D:/Dev/Python/widdler/tests/foo.py
Traceback (most recent call last):
  File "D:/Dev/Python/widdler/tests/foo.py", line 37, in <module>
    run_quickstart()
  File "D:/Dev/Python/widdler/tests/foo.py", line 30, in run_quickstart
    bucket = storage_client.create_bucket(bucket_name)
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\cloud\storage\client.py", line 229, in create_bucket
    bucket.create(client=self)
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\cloud\storage\bucket.py", line 278, in create
    data=properties, _target_object=self)
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\cloud\_http.py", line 290, in api_request
    headers=headers, target_object=_target_object)
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\cloud\_http.py", line 183, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\cloud\_http.py", line 212, in _do_request
    url=url, method=method, headers=headers, data=data)
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\auth\transport\requests.py", line 198, in request
    self._auth_request, method, url, request_headers)
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\auth\credentials.py", line 121, in before_request
    self.refresh(request)
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\oauth2\credentials.py", line 126, in refresh
    self._client_secret))
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\oauth2\_client.py", line 237, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\site-packages\google\oauth2\_client.py", line 108, in _token_endpoint_request
    response_body = response.data.decode('utf-8')
  File "D:\Miniconda3\envs\Python-2.7 Web\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by jonparrott** [comment]
@Osiris1975 this is pretty unusual. Can you use PyCharm to run a script that does this?

```python
import google.auth
credentials, project = google.auth.default()
print(type(credentials))
print(project is not None)
```

**Comment by Osiris1975** [comment]
Yes, that works:
```
<class 'google.oauth2.credentials.Credentials'>
True

Process finished with exit code 0
```
I think it's something wrong with the particular PyCharm project I'm trying to use the Google storage library with. If I run the quickstart sample code in a new project using a PyCharm run config, it works fine. So not a problem with the library itself.

**Comment by Osiris1975** [comment]
So definitely something with my Conda environment. Not a Google problem so I will close this.

**Comment by Osiris1975** [comment]
In case anyone else runs into this bizarre issue, I resolved it be deleting the .idea directory in my project and letting PyCharm rebuild it on restart.

**Comment by EffyF** [comment]
Hi i have the same problem it's from conda"CondaIndexError: Invalid index file: https://github.com/pri22296/beautifultable/tarball/0.4.0/osx-64/repodata.json: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte" this is the error, i have already uninstall beautifultable package but still this error show up every time i want to install something using conda
