### ISSUE TITLE
The line client = vision.ImageAnnotatorClient() throws an error in a different file.

### ISSUE THREAD

**Issue by TheNarwhalArmy** [GoogleCloudPlatform/python-docs-samples#1384]
## In which file did you encounter the issue?
image_annotator_pb2.py

C:\Users\ethan\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\vision_v1\proto\image_annotator_pb2.py

I did not change much b/c I don't really know why it actually is causing an error.

## Describe the issue
when I run the script I got from this link (https://cloud.google.com/vision/docs/detecting-labels#vision-label-detection-python) and change it so that it works for what I'm trying to do it gives the error:

Traceback (most recent call last):
  File "C:\Users\ethan\Desktop\test\test.py", line 29, in <module>
    detect_text()
  File "C:\Users\ethan\Desktop\test\test.py", line 10, in detect_text
    client = vision.ImageAnnotatorClient("Test-023baa8d2e3a.json")
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\vision_v1\gapic\image_annotator_client.py", line 93, in __init__
    image_annotator_pb2.ImageAnnotatorStub(channel))
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\vision_v1\proto\image_annotator_pb2.py", line 1989, in __init__
    self.BatchAnnotateImages = channel.unary_unary(
AttributeError: 'str' object has no attribute 'unary_unary'

**Comment by jonparrott** [comment]
It seems you passed in the credentials filename to the constructor:

```
client = vision.ImageAnnotatorClient("Test-023baa8d2e3a.json")
```

You should instead just set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable as documented [here](https://cloud.google.com/docs/authentication/getting-started) and then just:

```
client = vision.ImageAnnotatorClient()
```
