### ISSUE TITLE
Facing issue while running Python Flask web app on App Engine

### ISSUE THREAD

**Issue by sunnygoel8** [GoogleCloudPlatform/python-docs-samples#1412]
[CRF_FlaskApp.zip](https://github.com/GoogleCloudPlatform/python-docs-samples/files/1822286/CRF_FlaskApp.zip)
I'm facing following issue while running Python Flask web app on Google app engine. Earlier I was getting Flask module import issue. I fixed that by downgrading version to 0.12 and mentioned the same in app.yaml file also. Created a lib folder and installed Werkzeuz 0.12.2 library. 

Post deployment, started getting "Invalid argument" exception. Application is working fine in local development environment. Can someone help me fix the issue? I attached the application zip also. 

**Stack Trace**
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/p~flaskwebapp-python/20180317t182909.408380679033613111/main.py", line 62, in <module>
    app.run();
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/flask-0.12/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/base/data/home/apps/p~flaskwebapp-python/20180317t182909.408380679033613111/lib/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/base/data/home/apps/p~flaskwebapp-python/20180317t182909.408380679033613111/lib/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/base/data/home/apps/p~flaskwebapp-python/20180317t182909.408380679033613111/lib/werkzeug/serving.py", line 593, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/base/data/home/apps/p~flaskwebapp-python/20180317t182909.408380679033613111/lib/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_dist/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_dist/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_dist/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_dist/lib/python2.7/socket.py", line 227, in meth
    return getattr(self._sock,name)(*args)
  File **"/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 679, in bind
    raise _SystemExceptionFromAppError(e)
error: [Errno 22] Invalid argument**

**Comment by sunnygoel8** [comment]
Can anyone help me fix this issue ?

**Comment by patelnav** [comment]
It wasn't a Flask versioning issue. 
@google seems to be snoozing on this repo, not even a response! 
Get rid of the last line `app.run();` - it shouldn't be there. 

Then you run the app using `dev_appserver.py app.yaml`

**Comment by patelnav** [comment]
btw, I'm not sure where you got the link, but that looks like an old example. Please look at the latest [code here](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/flask/tutorial)

**Comment by engelke** [comment]
As mentioned above. the current code in the repository is correct. This report is for a quite old snapshot.
