### ISSUE TITLE
503 Connect Failed

### ISSUE THREAD

**Issue by WierZheng** [GoogleCloudPlatform/python-docs-samples#1416]
## Describe the issue

`python quickstart.py `

Traceback (most recent call last):
  File "quickstart.py", line 60, in <module>
    run_quickstart()
  File "quickstart.py", line 52, in run_quickstart
    response = client.recognize(config, audio)
  File "E:\PythonProjects\speech\env\lib\site-packages\google\cloud\speech_v1\gapic\speech_client.py", line 191, in recognize
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "E:\PythonProjects\speech\env\lib\site-packages\google\api_core\gapic_v1\method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "E:\PythonProjects\speech\env\lib\site-packages\google\api_core\retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "E:\PythonProjects\speech\env\lib\site-packages\google\api_core\retry.py", line 195, in retry_target
    last_exc)
  File "E:\PythonProjects\speech\env\lib\site-packages\six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling <functools.partial object at 0x065E03F0>, last exception: 503 Connect Failed

How to deal with this problem?

**Comment by WierZheng** [comment]
a good network Access to the Google but not over the wall  will help for  this
