### ISSUE TITLE
transcribe_streaming_indefinite still gives 65 sec duration error

### ISSUE THREAD

**Issue by eyaler** [GoogleCloudPlatform/python-docs-samples#1477]
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 76, in next
    return six.next(self._wrapped)
  File "C:\Anaconda3\lib\site-packages\grpc\_channel.py", line 347, in __next__
    return self._next()
  File "C:\Anaconda3\lib\site-packages\grpc\_channel.py", line 330, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.OUT_OF_RANGE, Exceeded maximum allowed stream duration of 65 seconds.)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\python\transcribe_streaming_indefinite.py", line 230, in <module>
    main(args.rate, args.audio_src)
  File "C:\Users\python\transcribe_streaming_indefinite.py", line 205, in main
    listen_print_loop(responses, stream)
  File "C:\Users\python\transcribe_streaming_indefinite.py", line 168, in listen_print_loop
    _record_keeper(with_results, stream))
  File "C:\Users\python\transcribe_streaming_mic.py", line 118, in listen_print_loop
    for response in responses:
  File "C:\Users\python\transcribe_streaming_indefinite.py", line 149, in _record_keeper
    for r in responses:
  File "C:\Users\python\transcribe_streaming_indefinite.py", line 165, in <genexpr>
    with_results = (r for r in responses if (
  File "C:\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 78, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.OutOfRange: 400 Exceeded maximum allowed stream duration of 65 seconds.

**Comment by nnegrey** [comment]
Hi, it looks like this was submitted while this file was still in progress during May, it appears to have been resolved. Please feel free to reopen this issue if that is not the case. 

Note: This sample is in a branch that was never published to master.
