### ISSUE TITLE
The initialization is very slow

### ISSUE THREAD

**Issue by mmaaww** [GoogleCloudPlatform/python-docs-samples#1479]
I recently started to try wavenet cloud service. Every time my service started or after long idle time, the wavenet service takes long time to respond, about 20-40 seconds. Afterwards, the response is promptly (<1 second). And I do see the following errors every time. It seems that the authentication takes a long time, but not exactly sure. Can someone help me on this?

05-13 20:36 google.auth.transport.requests DEBUG    Making request: POST https://accounts.google.com/o/oauth2/token
05-13 20:36 urllib3.connectionpool DEBUG    Starting new HTTPS connection (2): accounts.google.com
05-13 20:36 google.api_core.retry DEBUG    Retrying due to 503 Deadline Exceeded, sleeping 0.0s ...
05-13 20:36 root         ERROR    AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f9148823410>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    callback_state, callback))
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/grpc.py", line 65, in _get_authorization_headers
    headers)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/credentials.py", line 121, in before_request
    self.refresh(request)
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/_client.py", line 106, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 124, in __call__
    six.raise_from(new_exc, caught_exc)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
TransportError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'),))

**Comment by nnegrey** [comment]
This looks to have been resolved by the linked issue or it's due to a refresh token being requested. 

If that's not the case, please feel free to reopen the issue. Thanks! :)
