### ISSUE TITLE
Conversion not working for Raspberry Pi,  Adafruit-i2s-mems-microphone SPH0645 for Continues Speech to Text conversion Using speech Api. 

### ISSUE THREAD

**Issue by HiteshPA** [GoogleCloudPlatform/python-docs-samples#1507]
# ** Speech Api mot working with Rpi and i2s microphone .****

 In **Virtual envirment** I have set up the Google speech client api and Set up the GOOGLE_APPLICATION_CREDENTIALS but after running the Python sample code # **transcribe_streaming_mic.py** . it does work but it stuck after and gives the error after 60 sec (I know the limit is 60 sec streaming)  

 ```
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed**
Traceback (most recent call last):
  File "/home/pi/Desktop/Project/env/lib/python3.5/site-packages/google/api_core/grpc_helpers.py", line 76, in next
    return six.next(self._wrapped)
  File "/home/pi/Desktop/Project/env/lib/python3.5/site-packages/grpc/_channel.py", line 341, in __next__
    return self._next()
  File "/home/pi/Desktop/Project/env/lib/python3.5/site-packages/grpc/_channel.py", line 324, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.OUT_OF_RANGE, Exceeded maximum allowed stream duration of 65 seconds.)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "exap.py", line 193, in <module>
    main()
  File "exap.py", line 189, in main
    listen_print_loop(responses)
  File "exap.py", line 128, in listen_print_loop
    for response in responses:
  File "/home/pi/Desktop/Project/env/lib/python3.5/site-packages/google/api_core/grpc_helpers.py", line 78, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.OutOfRange: 400 Exceeded maximum allowed stream duration of 65 seconds.
```
The Microphone is working perfectly with Audacity, Alsa and Arecord perfectly. 

**# sudo nano ~/.asoundrc**

```
pcm.dmic_hw {
        type hw
        card sndrpisimplecar
        channels 2
        format S32_LE
}
pcm.dmic_sv {
        type softvol
        slave.pcm dmic_hw
        control {
                name "Boost Capture Volume"
                card sndrpisimplecar
        }
        min_dB -1.0
        max_dB 50.0
}
```
Can you please help on this?

**Comment by nnegrey** [comment]
Hi, which part of the sample is causing the issue?

**Comment by nnegrey** [comment]
Going to close this issue due to how old it is, please feel free to reopen. :)
