### ISSUE TITLE
Request contains no InfoTypes or CustomInfoTypes, however an InfoTypeTransformation was included that had no InfoType name included.

### ISSUE THREAD

**Issue by rendybjunior** [GoogleCloudPlatform/python-docs-samples#1513]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/895cbf54527abb3e16817f3d6d6c0c678c2b52b6/dlp/deid.py#L76

Try the sample and get this problem

google.api_core.exceptions.InvalidArgument: 400 Request contains no InfoTypes or CustomInfoTypes, however an InfoTypeTransformation was included that had no InfoType name included. You must specify InfoTypes or CustomInfoTypes within InspectConfig in this case so that Cloud DLP can determine what to inspect for.

Full error
(dlp) ➜  dlp git:(master) ✗ python deid.py deid_fpe tvlk-realtime-stg "My SSN is 372819127" <keyname> <wrapped key>
Traceback (most recent call last):
  File "deid.py", line 542, in <module>
    surrogate_type=args.surrogate_type)
  File "deid.py", line 149, in deidentify_with_fpe
    parent, deidentify_config=deidentify_config, item=item)
  File "/anaconda2/lib/python2.7/site-packages/google/cloud/dlp_v2/gapic/dlp_service_client.py", line 552, in deidentify_content
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/anaconda2/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/anaconda2/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/anaconda2/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/anaconda2/lib/python2.7/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/anaconda2/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 56, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/anaconda2/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value

**Comment by engelke** [comment]
The test code calling this function was missing a parameter, which was corrected in PR #1784.
