### ISSUE TITLE
All texttospeech calls fail with: StatusCode.UNIMPLEMENTED, Method not found

### ISSUE THREAD

**Issue by juliusspencer** [GoogleCloudPlatform/python-docs-samples#1528]
## In which file did you encounter the issue?

python-docs-samples/texttospeech/cloud-client/synthesize_file.py

### Did you change the file? If so, how?

No

## Describe the issue
When I try to use any of the commands I get an error:

> google.api_core.exceptions.MethodNotImplemented: 501 Method not found.
(trace below)

I have GOOGLE_APPLICATION_CREDENTIALS configured and exported. I have enabled the API.

Commands that fail the same way:
`python quickstart.py`
`python list_voices.py`
`python synthesize_file.py --text ~/video_text.txt`

My directory is:
`(env) jspencer@cloudshell:~/python-docs-samples/texttospeech/cloud-client$`

Trace:
```
(env) jspencer@cloudshell:~/python-docs-samples/texttospeech/cloud-client$ python list_voices.py
Traceback (most recent call last):
  File "/home/jspencer/python-docs-samples/texttospeech/cloud-client/env/lib/python3.5/site-packages/google/api_core/grpc_helpers.py", line 54, in error_remapped_ca
llable
    return callable_(*args, **kwargs)
  File "/home/jspencer/python-docs-samples/texttospeech/cloud-client/env/lib/python3.5/site-packages/grpc/_channel.py", line 500, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/jspencer/python-docs-samples/texttospeech/cloud-client/env/lib/python3.5/site-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Method not found.)>
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "list_voices.py", line 56, in <module>
    list_voices()
  File "list_voices.py", line 31, in list_voices
    voices = client.list_voices()
  File "/home/jspencer/python-docs-samples/texttospeech/cloud-client/env/lib/python3.5/site-packages/google/cloud/texttospeech_v1/gapic/text_to_speech_client.py", line 182, in list_voices
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/home/jspencer/python-docs-samples/texttospeech/cloud-client/env/lib/python3.5/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/jspencer/python-docs-samples/texttospeech/cloud-client/env/lib/python3.5/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/home/jspencer/python-docs-samples/texttospeech/cloud-client/env/lib/python3.5/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/home/jspencer/python-docs-samples/texttospeech/cloud-client/env/lib/python3.5/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/jspencer/python-docs-samples/texttospeech/cloud-client/env/lib/python3.5/site-packages/google/api_core/grpc_helpers.py", line 56, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.MethodNotImplemented: 501 Method not found.
```

**Comment by tetelestia** [comment]
I'm getting this error as well. Downgrading `google-cloud-texttospeech` to version `0.1.0` has fixed it temporarily.

**Comment by nnegrey** [comment]
Rolling back to `0.1.0` while things get settled, sorry about that. 

https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1539
