### ISSUE TITLE
[Functions] Manually testing Slack tutorial with CURL returns invalid request

### ISSUE THREAD

**Issue by ptiger10** [GoogleCloudPlatform/python-docs-samples#1642]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/functions/slack

### Did you change the file? If so, how?

Changed  `verify_web_hook()` to isolate source of error.

Was:
```
def verify_web_hook(form):
    if not form or form.get('token') != config['SLACK_TOKEN']:
        raise ValueError('Invalid request/credentials.')
```

Changed to:
```
def verify_web_hook(form):
    if not form:
        raise ValueError('Invalid request.')
```

## Describe the issue
The function works correctly when triggered by the Slack Slash command, but it breaks when tested manually. By changing `request.form` to `request.get_json()`, the problem is simply reversed.

The tutorial reads:
"Test the command manually:
`curl -X POST "https://YOUR_REGION-YOUR_PROJECT_ID.cloudfunctions.net/kg_search" -H "Content-Type: application/json" --data '{"token":"YOUR_SLACK_TOKEN","text":"giraffe"}'`"

After substituting in my constants, I ran this in Terminal. Terminal returns:
`Error: could not handle the request`

Stackdriver Logs returns: 
```
Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions_v1beta2/worker.py", line 251, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions_v1beta2/worker.py", line 171, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions_v1beta2/worker.py", line 164, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 93, in kg_search verify_web_hook(request.form) File "/user_code/main.py", line 32, in verify_web_hook raise ValueError('Invalid request.') ValueError: Invalid request.
```

Separately tried removing `verify_web_hook()` altogether and log returned:
`400 Bad Request: The browser (or proxy) sent a request that this server could not understand.`

Full log:
```
Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions_v1beta2/worker.py", line 251, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions_v1beta2/worker.py", line 171, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions_v1beta2/worker.py", line 164, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 94, in kg_search kg_search_response = make_search_request(request.form['text']) File "/env/local/lib/python3.7/site-packages/werkzeug/datastructures.py", line 431, in __getitem__ raise exceptions.BadRequestKeyError(key) werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

Tried a different manual test in Cloud Functions console > Function details > Testing tab:
**Triggering event**:
`{"text":"giraffe"}`

**Output**:
```
Error: function crashed. Details:
Invalid request.
```

Terminal raises an error regardless of Content-Type in my header. Have tried:
"Content-Type: application/json"
"Content-Type: application/x-www-form-urlencoded"
"Content-Type: application/multipart/form-data"

In another GCP project, I was able to resolve this error by changing references in code from `request.form` to `request.get_json.` However, implementing that solution here has the following effect:

1. The manual Terminal test provided in the tutorial is now successful.
2. The Cloud Functions > Function details > Testing tab is now successful.
Both return:
```
{"attachments":[{"color":"#3367d6","image_url":"http://t0.gstatic.com/images?q=...","text":"The giraffe...}
```

3. The function **breaks** when triggered by the Slash command in Slack. It now returns:
```
Darn - that slash command didn't work (error message: `500_service_error`).
```
Digging into it a bit more, when either manual test is triggered, request.form returns an empty `ImmutableMultiDict([])`. 

In summary, it seems that the Slack API formats its slash command requests as forms, which can be parsed only with `request.form`. However, the two manual testing mechanisms return an error when passed into `request.form,` and succeed when passed into `request.get_json.`

The below workaround fixes the issue, but I'm wondering if it is the recommended solution?
```
def sanitize_request(request: 'Flask.request') -> Dict:
    "Return request.get_json() if request.form not available"
    data = request.form
    if not data:
        data = request.get_json()
    if data is None:
        return 'Request must include data payload'
    return data 

def kg_search(request):
    data = sanitize_request(request)
    if request.method != 'POST':
        return 'Only POST requests are accepted', 405

    verify_web_hook(data)
    kg_search_response = make_search_request(data.get('text'))
    return jsonify(kg_search_response)
```

---
Other context on my setup:
```
$ pip freeze | grep Flask
Flask==1.0.2

$ curl -V
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
```

**Comment by engelke** [comment]
It looks like the sample code is correct as shown. As you say, it works with requests from Slack. The curl command shown to try it out is wrong. It does not match what Slack sends. The correct command would be:

curl -X POST "https://YOUR_REGION-YOUR_PROJECT_ID.cloudfunctions.net/kg_search" --data 'token=YOUR_SLACK_TOKEN&text=giraffe'

A bug has been submitted to fix the documentation. Thanks for submitting this issue.
