### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OperationsStub'

### ISSUE THREAD

**Issue by jinser** [GoogleCloudPlatform/python-docs-samples#1693]
## In which file did you encounter the issue?
speech/cloud-client/quickstart.py

### Did you change the file? If so, how?

No, straight from cloning the project

## Describe the issue

Python 2.7.6

Followed the Readme instructions (https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/speech/cloud-client) to clone the python samples and and installed dependencies.

The only requirements.txt that was ran was from speech/cloud-client/requirements.txt

However, after setting up authentication by running export GOOGLE_APPLICATION_CREDENTIALS=, I ran the command python quickstart.py.

Following error was received:
$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 60, in <module>
    run_quickstart()
  File "quickstart.py", line 32, in run_quickstart
    client = speech.SpeechClient()
  File "/home/ubuntu/workspace/speech_tests/env/local/lib/python2.7/site-packages/google/cloud/speech_v1/gapic/speech_client.py", line 112, in __init__
    credentials=credentials,
  File "/home/ubuntu/workspace/speech_tests/env/local/lib/python2.7/site-packages/google/cloud/speech_v1/gapic/transports/speech_grpc_transport.py", line 73, in __init__
    self._operations_client = google.api_core.operations_v1.OperationsClient(channel)
  File "/home/ubuntu/workspace/speech_tests/env/local/lib/python2.7/site-packages/google/api_core/operations_v1/operations_client.py", line 59, in __init__
    self.operations_stub = operations_pb2.OperationsStub(channel)
AttributeError: 'module' object has no attribute 'OperationsStub'

**Comment by engelke** [comment]
The example seems to work now under Python 2.7. The required version of google-cloud-speech was updated on September 29 in PR #1702, which might have fixed the issue. Please reopen this issue if the problem is still there with the latest version on Github. Thanks.
