### ISSUE TITLE
monitoring/api/v3/alerts-client/snippets.py can't restore from backup due to masked auth_token

### ISSUE THREAD

**Issue by Guoest** [GoogleCloudPlatform/python-docs-samples#1852]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/monitoring/api/v3/alerts-client/snippets.py

### Did you change the file? If so, how?
No change

## Describe the issue
I'm using slack channel as my notification channel. And with `snippets.py backup` I'm able to generate a `backup.json`, however, the channel field has `"auth_token": "***********************************************************************9684"` which is masked. 

Then when I use `snippets.py restore` it failed due to obscured auth_token. Error pasted below.
I was unable to retrieve unmasked auth_token from stackdriver. 

Updating channel 
Traceback (most recent call last):
  File "snippets.py", line 314, in <module>
    restore(project_name())
  File "snippets.py", line 152, in restore
    channel_client.update_notification_channel(channel)
  File "/Users/yguo057/PycharmProjects/python-docs-samples/monitoring/api/v3/alerts-client/env/lib/python2.7/site-packages/google/cloud/monitoring_v3/gapic/notification_channel_service_client.py", line 692, in update_notification_channel
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/Users/yguo057/PycharmProjects/python-docs-samples/monitoring/api/v3/alerts-client/env/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/yguo057/PycharmProjects/python-docs-samples/monitoring/api/v3/alerts-client/env/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/Users/yguo057/PycharmProjects/python-docs-samples/monitoring/api/v3/alerts-client/env/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/Users/yguo057/PycharmProjects/python-docs-samples/monitoring/api/v3/alerts-client/env/lib/python2.7/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/yguo057/PycharmProjects/python-docs-samples/monitoring/api/v3/alerts-client/env/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 61, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/Users/yguo057/PycharmProjects/python-docs-samples/monitoring/api/v3/alerts-client/env/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.InvalidArgument: 400 Field notification_channel.labels[auth_token] had an invalid value of "***********************************************************************9684": Value seems to be obscured.

**Comment by engelke** [comment]
The page at [https://cloud.google.com/monitoring/alerts/using-alerting-api](https://cloud.google.com/monitoring/alerts/using-alerting-api) warns that "The restoration process is more complex than the original back-up" and shows cases where the saved JSON file needs to be edited to be restorable. This is one of those cases.

The documentation of the API states that:

`Fields containing sensitive information like authentication tokens or contact info are only partially populated on retrieval.
`

So to restore an authenticated channel like this one you will have to edit the JSON, replacing the masked token with a valid one. That valid token would have to be provided by Slack, and you will have to ask them how to find it.
