### ISSUE TITLE
How to save the mic streamed data for other analysis purpose?

### ISSUE THREAD

**Issue by auvilink** [GoogleCloudPlatform/python-docs-samples#1947]
Hi, there, I tried to save the streamed data and convert them to integers (for other analysis purpose but encounters error which I could not resolve.

## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py

### Did you change the file? If so, how?

I added two lines of code in generator() function.

line 39: import struct

line 108: newdata = struct.unpack('hh2',data)

## Describe the issue

Traceback (most recent call last):
  File "transcribe_streaming_mic_emotion.py", line 196, in <module>
    main()
  File "transcribe_streaming_mic_emotion.py", line 192, in main
    listen_print_loop(responses)
  File "transcribe_streaming_mic_emotion.py", line 131, in listen_print_loop
    for response in responses:
  File "/Users/michaelhe/ml/env/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 81, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/Users/michaelhe/ml/env/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.Unknown: None Exception iterating requests!

**Comment by nnegrey** [comment]
Hey, take a look at the PyAudio docs for saving the audio.
https://people.csail.mit.edu/hubert/pyaudio/#docs

**Comment by rjtmehta99** [comment]
@auvilink - were you able to save the streamed audio?
