### ISSUE TITLE
pip install google-appengine fails with SSL error

### ISSUE THREAD

**Issue by kolinko** [GoogleCloudPlatform/python-docs-samples#2009]
## In which file did you encounter the issue?

This piece of code breaks

```
$ python
Python 3.7.2 (default, Jan 13 2019, 12:50:01) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.appengine.api import memcache
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.appengine'
```

And it's a cutout from this:

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/6f5f3bcb81779679a24e0964a6c57c0c7deabfac/appengine/standard/memcache/guestbook/main.py

## Describe the issue

I'm trying to install google-appengine using pip install, and it fails like below. When googling for the issue, I found that I need to add --trusted-hosts to ignore the https checks, but **it doesn't seem to help in my case.**

I also just reinstalled the whole python3.7 setup on my MacOS, all the libraries and so on. Is there something I'm doing wrong?

```
$ pip install --trusted-host pypi.python.org google-appengine
Collecting google-appengine
  Using cached https://files.pythonhosted.org/packages/8d/f1/405f6a85407673cd628fb29fadf84a3dd9f533551a9236609e55e04ad22c/google-appengine-1.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/local/lib/python3.7/site-packages/setuptools/version.py:1: UserWarning: Module google was already imported from None, but /private/var/folders/yv/sxpmnxx10_3_58zx8qgb4_800000gn/T/pip-install-tw_w7x_t/google-appengine is being added to sys.path
      import pkg_resources
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/ez_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/yv/sxpmnxx10_3_58zx8qgb4_800000gn/T/pip-install-tw_w7x_t/google-appengine/setup.py", line 3, in <module>
        ez_setup.use_setuptools()
      File "/usr/local/lib/python3.7/site-packages/ez_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/usr/local/lib/python3.7/site-packages/ez_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "/usr/local/lib/python3.7/site-packages/ez_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/yv/sxpmnxx10_3_58zx8qgb4_800000gn/T/pip-install-tw_w7x_t/google-appengine/

```

**Comment by andrewsg** [comment]
Hi Kolinko, sorry for the confusion. I'm afraid the specific sample code you are looking at is only for our Google App Engine Python 2.7 runtime, which has a bespoke GAE-only client library called google.appengine. In our new Python 3.7 runtime, it is not necessary to use google.appengine and instead we recommend use of the Cloud Client libraries that support any platform (including GAE). If you need help finding the equivalent GAE Python 3.7 example code, please let me know what you're trying to accomplish at a high level in a comment and I'll try to assist.
