### ISSUE TITLE
How make import speech_v1p1beta1 as speech works in google-cloud?

### ISSUE THREAD

**Issue by farzane-mif** [GoogleCloudPlatform/python-docs-samples#2074]
I want to use google-cloud for speech to text conversion. After installing google-cloud,I get import error by this:

`from google.cloud import speech_v1p1beta1 as speech`
import error:

  ```
  from google.cloud import speech_v1p1beta1 as speech
    Traceback (most recent call last): File "<ipython-input-26-aca8ce269e21>", line 1, in <module>
    from google.cloud import speech_v1p1beta1 as speech

  File "C:\ProgramData\Anaconda2\lib\site-packages\google\cloud\speech_v1p1beta1\__init__.py", line 17, in <module>
    from google.cloud.speech_v1p1beta1 import types

  File "C:\ProgramData\Anaconda2\lib\site-packages\google\cloud\speech_v1p1beta1\types.py", line 22, in <module>
    from google.cloud.speech_v1p1beta1.proto import cloud_speech_pb2

  File "C:\ProgramData\Anaconda2\lib\site-packages\google\cloud\speech_v1p1beta1\proto\cloud_speech_pb2.py", line 18, in <module>
    from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2

ImportError: No module named ap
```

**Comment by nnegrey** [comment]
Hi, could you try running:
`pip install --upgrade google-cloud-speech`

Does that help?

**Comment by farzane-mif** [comment]
I already Upgraded it. This error happened after using this command.

Any other solution??

**Comment by nnegrey** [comment]
Is there a specific sample you're trying to follow for this?

**Comment by nnegrey** [comment]
Gonna close this for now, feel free to re-open. :)

**Comment by shankarkarande** [comment]
> Hi, could you try running: `pip install --upgrade google-cloud-speech`
> 
> Does that help?

Thanks !! It works for me !!
