### ISSUE TITLE
google.api_core.exceptions.GoogleAPICallError: None Unexpected state: Long-running operation had neither response nor error set.

### ISSUE THREAD

**Issue by shubhrajodiya** [GoogleCloudPlatform/python-docs-samples#2109]
I am trying to transcribe long audio file but getting the error.

def transcribe_gcs(gcs_uri):
    """Asynchronously transcribes the audio file specified by the gcs_uri."""
    from google.cloud import speech
    from google.cloud.speech import enums
    from google.cloud.speech import types
    client = speech.SpeechClient()

    audio = types.RecognitionAudio(uri=gcs_uri)
    config = types.RecognitionConfig(
        encoding=enums.RecognitionConfig.AudioEncoding.FLAC,
        sample_rate_hertz=16000,
        language_code='en-US')

    operation = client.long_running_recognize(config, audio)

    print('Waiting for operation to complete...')
    response = operation.result(timeout=90)

    # Each result is for a consecutive portion of the audio. Iterate through
    # them to get the transcripts for the entire audio file.
    for result in response.results:
        # The first alternative is the most likely one for this portion.
        print(u'Transcript: {}'.format(result.alternatives[0].transcript))
        print('Confidence: {}'.format(result.alternatives[0].confidence))

transcribe_gcs("gs://missdonna-data/try.mp3")

Error :-

Traceback (most recent call last):
  File "app.py", line 27, in <module>
    transcribe_gcs("gs://missdonna-data/try.mp3")
  File "app.py", line 17, in transcribe_gcs
    response = operation.result(timeout=90)
  File "/home/shubham/.local/lib/python2.7/site-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.GoogleAPICallError: None Unexpected state: Long-running operation had neither response nor error set.

How can I fix it ?

**Comment by shubhrajodiya** [comment]
issue resolved

use .wav format and if still you're getting the same error try to gather more information about the encoding you are using in the file.
