### ISSUE TITLE
Problem running endpoints oauth client

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/python-docs-samples#310]
```
$ python clients/google-jwt-client.py https://ep-dot-cbro-scratch.appspot.com $KEY ~/endpoints-client/oauth-secret.json
Error processing line 2 of /usr/local/lib/python2.7/dist-packages/googleapis_common_protos-1.1.0-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Traceback (most recent call last):
  File "clients/google-jwt-client.py", line 92, in <module>
    main(args.host, args.api_key, args.service_account_file)
  File "clients/google-jwt-client.py", line 73, in main
    signed_jwt = generate_jwt(service_account_file)
  File "clients/google-jwt-client.py", line 32, in generate_jwt
    service_account_file)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 195, in from_json_keyfile_name
    return cls._from_parsed_json_keyfile(client_credentials, scopes)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 161, in _from_parsed_json_keyfile
    'Expected', SERVICE_ACCOUNT)
ValueError: ('Unexpected credentials type', None, 'Expected', 'service_account')
```

**Comment by broady** [comment]
I was running the wrong client. D'oh.
