### ISSUE TITLE
[nox] Test fails when nox fails to download dependencies

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3485]
Maybe we should retry few times.

Example log:
```
 Using noxfile-template from parent folder (/tmpfs/src/github/python-docs-samples).

Running session py-3.7
Creating virtual environment (virtualenv) using python3.7 in .nox/py-3-7
pip install -r requirements.txt
Command pip install -r requirements.txt failed with exit code 2:
Ignoring tensorflow: markers 'python_version < "3.0"' don't match your environment
Collecting tensorflow==2.0.1
  Downloading tensorflow-2.0.1-cp37-cp37m-manylinux2010_x86_64.whl (86.3 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/tmpfs/src/github/python-docs-samples/ml_engine/online_prediction/.nox/py-3-7/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/tmpfs/src/github/python-docs-samples/ml_engine/online_prediction/.nox/py-3-7/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/tmpfs/src/github/python-docs-samples/ml_engine/online_prediction/.nox/py-3-7/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/usr/local/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by tmatsuo** [comment]
The first option came to mind is to use `backoff` in our `noxfile-template.py`.
I think we can retry upon [`nox.command.CommandFailed`](https://github.com/theacodes/nox/blob/b3c600c054761143703d67c8ba0afc791f13f267/nox/command.py#L24).

**Comment by kurtisvg** [comment]
Are these happening frequently enough that's it's worth adding logic for this? Or was this a one off error?

**Comment by tmatsuo** [comment]
I have only seen one time. It's one off, but potentially it can happen anytime.
It's worth adding in my opinion, but there is also a downside of requiring `backoff` locally.

Other option is to add retry to `nox` itself.

**Comment by tmatsuo** [comment]
Let's see how often we'll see this. I'll add occurrences to this issue whenever I see the same error.

**Comment by tmatsuo** [comment]
According to https://pip.pypa.io/en/stable/reference/pip/

It seems that pip already retries 5 times. In that case, I don't think more retry would improve the situation. Closing.
