### ISSUE TITLE
[dialogflow] flake: Operation did not complete within the designated timeout.

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3490]
[build](https://source.cloud.google.com/results/invocations/0b452825-4d8c-442d-8aac-6fc0f4a8078d/targets/github%2Fpython-docs-samples%2Fdialogflow%2Fcloud-client/tests)

Log:
```
Traceback (most recent call last):
  File "/tmpfs/src/github/python-docs-samples/dialogflow/cloud-client/create_document_test.py", line 53, in test_create_document
    'text/html', 'FAQ', 'https://cloud.google.com/storage/docs/faq')
  File "/tmpfs/src/github/python-docs-samples/dialogflow/cloud-client/document_management.py", line 63, in create_document
    document = response.result(timeout=90)
  File "/tmpfs/src/github/python-docs-samples/dialogflow/cloud-client/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/future/polling.py", line 125, in result
    self._blocking_poll(timeout=timeout)
  File "/tmpfs/src/github/python-docs-samples/dialogflow/cloud-client/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/future/polling.py", line 107, in _blocking_poll
    "Operation did not complete within the designated " "timeout."
concurrent.futures._base.TimeoutError: Operation did not complete within the designated timeout.
```

**Comment by tmatsuo** [comment]
@nnegrey I'll take this and try to fix it tomorrow, but if you've already started working on this, feel free to take it back.

**Comment by tmatsuo** [comment]
Build cop bot caught it #3672
