### ISSUE TITLE
[blog] flake: google.api_core.exceptions.Aborted: 409 too much contention on these datastore entities.

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3548]
blog/introduction_to_data_models_in_cloud_datastore
wiki_test.test_main

[Build](https://source.cloud.google.com/results/invocations/acf625e9-f999-4b7f-95ad-7efb9eb54086/targets/github%2Fpython-docs-samples%2Fblog%2Fintroduction_to_data_models_in_cloud_datastore/tests)

Log:
```
Traceback (most recent call last):
  File "/tmpfs/src/github/python-docs-samples/blog/introduction_to_data_models_in_cloud_datastore/wiki_test.py", line 25, in test_main
    main(PROJECT)
  File "/tmpfs/src/github/python-docs-samples/blog/introduction_to_data_models_in_cloud_datastore/wiki.py", line 78, in main
    save_page(ds, 'page1', '2')
  File "/tmpfs/src/github/python-docs-samples/blog/introduction_to_data_models_in_cloud_datastore/wiki.py", line 58, in save_page
    ds.put(current)
...
...
google.api_core.exceptions.Aborted: 409 too much contention on these datastore entities. please try again. entity groups: [(app=s~python-docs-samples-tests, page, "page1")]
```

**Comment by tmatsuo** [comment]
We haven't seen this failure for a while. Maybe it's mitigated by having intervals between periodic builds. Closing.
