### ISSUE TITLE
[translate] flake: `translate/automl::dataset_test.test_dataset_list_get` fails with 404

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3754]
[Build](https://source.cloud.google.com/results/invocations/fb675316-84fe-4ff0-9eb2-0da1ffd5e89e/targets/github%2Fpython-docs-samples%2Ftranslate%2Fautoml/tests)

```
Traceback (most recent call last):
  File "/tmpfs/src/github/python-docs-samples/translate/automl/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/tmpfs/src/github/python-docs-samples/translate/automl/.nox/py-3-7/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/tmpfs/src/github/python-docs-samples/translate/automl/.nox/py-3-7/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Requested entity was not found."
	debug_error_string = "{"created":"@1589340600.880313292","description":"Error received from peer ipv4:172.217.193.95:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Requested entity was not found.","grpc_status":5}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmpfs/src/github/python-docs-samples/translate/automl/dataset_test.py", line 66, in test_dataset_list_get
    project_id, compute_region, dataset_id
  File "/tmpfs/src/github/python-docs-samples/translate/automl/automl_translation_dataset.py", line 141, in get_dataset
    dataset = client.get_dataset(dataset_full_id)
  File "/tmpfs/src/github/python-docs-samples/translate/automl/.nox/py-3-7/lib/python3.7/site-packages/google/cloud/automl_v1beta1/gapic/auto_ml_client.py", line 514, in get_dataset
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/tmpfs/src/github/python-docs-samples/translate/automl/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/tmpfs/src/github/python-docs-samples/translate/automl/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/tmpfs/src/github/python-docs-samples/translate/automl/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/tmpfs/src/github/python-docs-samples/translate/automl/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/tmpfs/src/github/python-docs-samples/translate/automl/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.NotFound: 404 Requested entity was not found.
```

**Comment by tmatsuo** [comment]
Because this is rarely happening and this directory will be removed soon (see #3766), I'd just close this.
