### ISSUE TITLE
vision: vision/automl/automl_vision_edge_container_predict_test.test_edge_container_predict failed with missing docker image

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3828]
(Build)[https://source.cloud.google.com/results/invocations/fe90a7a5-508a-46db-bc85-4f102c14bb96/targets/github%2Fpython-docs-samples%2Fvision%2Fautoml/tests]

Log:
Traceback (most recent call last):
  File "/tmpfs/src/github/python-docs-samples/vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py", line 63, in edge_container_predict_server_port
    subprocess.check_output(['docker', 'pull', CPU_DOCKER_GCS_PATH])
  File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'pull', 'gcr.io/automl-vision-ondevice/gcloud-container-1.12.0:latest']' returned non-zero exit status 1.

stderr:
Error response from daemon: Get https://gcr.io/v2/automl-vision-ondevice/gcloud-container-1.12.0/manifests/latest: denied: Permission denied: Consumer 'project:automl-vision-ondevice' has been suspended.

**Comment by genquan9** [comment]
Thanks for the update and fix!
