### ISSUE TITLE
[datalabeling] flake: 500 "Fail to get project number for the project id"

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3995]
[build](https://source.cloud.google.com/results/invocations/aa54fad1-1d42-47a7-8dea-84994826e91c/targets)

log

```
Traceback (most recent call last):
  File "/workspace/datalabeling/.nox/py-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/workspace/datalabeling/.nox/py-3-8/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/workspace/datalabeling/.nox/py-3-8/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Fail to get project number for the project id: python-docs-samples-tests"
	debug_error_string = "{"created":"@1591403517.021122412","description":"Error received from peer ipv4:172.217.203.81:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Fail to get project number for the project id: python-docs-samples-tests","grpc_status":13}"
```

**Comment by tmatsuo** [comment]
Haven't seen this over a month, closing
