### ISSUE TITLE
[py-2.7] debug disabled app engine test

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#4076]
[Build](https://source.cloud.google.com/results/invocations/25de3e45-6db2-4189-b03a-4e8695d6f6d2/targets)

Directory:
appengine/standard/migration/ndb/overview

The log:
```
Traceback (most recent call last):
  File "/workspace/appengine/standard/migration/ndb/overview/main_test.py", line 26, in test_app
    response = app.get('/')
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/flask/testing.py", line 227, in open
    follow_redirects=follow_redirects,
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/workspace/appengine/standard/migration/ndb/overview/main.py", line 48, in display_guestbook
    greetings = Greeting.query_book(ancestor_key).fetch(20)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/google/cloud/ndb/query.py", line 1229, in wrapper
    return wrapped(self, *dummy_args, _options=query_options)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/google/cloud/ndb/utils.py", line 78, in wrapper
    return wrapped(*args, **new_kwargs)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/google/cloud/ndb/utils.py", line 110, in positional_wrapper
    return wrapped(*args, **kwds)
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/google/cloud/ndb/query.py", line 1731, in fetch
    return self.fetch_async(_options=kwargs["_options"]).result()
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/google/cloud/ndb/tasklets.py", line 193, in result
    self.check_success()
  File "/workspace/appengine/standard/migration/ndb/overview/.nox/py-2-7/lib/python2.7/site-packages/google/cloud/ndb/tasklets.py", line 140, in check_success
    raise self._exception
FailedPrecondition: 400 no matching index found. recommended index is:
- kind: Greeting
  ancestor: yes
  properties:
  - name: date
    direction: desc
```

**Comment by engelke** [comment]
See if datastore index needs to be created in test project to fix this.
