### ISSUE TITLE
Unable to list pubsub topics using service account credentials

### ISSUE THREAD

**Issue by jaychan-q** [GoogleCloudPlatform/python-docs-samples#4098]
## In which file did you encounter the issue?

pubsub/cloud-client/publisher.py 

### Did you change the file? If so, how?

No

## Describe the issue

Exported the service account credentials to env file as below.
export GOOGLE_APPLICATION_CREDENTIALS=Downloads/secops-testing-project-7bba9ff.json

The above service account has pubsub admin access. 
Ran the following command

python3 publisher.py secops-testing-project list 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "User not authorized to perform this action."
	debug_error_string = "{"created":"@1592293989.195739000","description":"Error received from peer ipv4:172.217.0.42:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"User not authorized to perform this action.","grpc_status":7}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "publisher.py", line 320, in <module>
    list_topics(args.project_id)
  File "publisher.py", line 38, in list_topics
    for topic in publisher.list_topics(project_path):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 212, in _items_iter
    for page in self._page_iter(increment=False):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 243, in _page_iter
    page = self._next_page()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 534, in _next_page
    response = self._method(self._request)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.PermissionDenied: 403 User not authorized to perform this action.
```

**Comment by kurtisvg** [comment]
@jaychan-q Can you try again using an absolute path for your credentials?

**Comment by jaychan-q** [comment]
@kurtisvg  tried it and does not work still. 

```
$ env|grep -i google_app
GOOGLE_APPLICATION_CREDENTIALS=/Users/jaychan/Downloads/secops-testing-project-7bba9ffa9133.json
```

**Comment by kurtisvg** [comment]
Unfortunately, I'm unable to replicate this - the sample works fine when I run it. Can you double check the following and see if it helps?

1. Make sure that you are using the latest version of the dependencies `pip install --upgrade -r requirements.txt`
1. Your service account is in the same project you are trying to use
1. Your project is set with `gcloud config set project`

**Comment by jaychan-q** [comment]
@kurtisvg  after much troubleshooting with my colleague, found the issue. Its same as here.
https://stackoverflow.com/questions/55725726/service-accounts-permissions

I had created the service account , deleted it and recreated with same name. For my life i would have never thought it will fail. 

Finally removed the roles and reassigned and works like a charm. Thanks for your help.

**Comment by kurtisvg** [comment]
Glad you figured it out!
