### ISSUE TITLE
unable to get permission in iot/manager examples

### ISSUE THREAD

**Issue by KKKKKyle** [GoogleCloudPlatform/python-docs-samples#4134]
## In which file did you encounter the issue?
python-docs-samples/iot/api-client/manager/manager.py

### Did you change the file? If so, how?

No

## Describe the issue

I used exactly the same command in the example as I used yesterday (with authentication set up):

```
python manager.py       --project_id=TestIoT       --cloud_region=us-central1       --service_account_json=$HOME/service_account.json       list-registries
```

but today I got the following issue:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "The caller does not have permission"
	debug_error_string = "{"created":"@1592618145.761600000","description":"Error received from peer ipv4:172.217.4.74:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"The caller does not have permission","grpc_status":7}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manager.py", line 1041, in <module>
    run_command(args)
  File "manager.py", line 977, in run_command
    run_create(args)
  File "manager.py", line 893, in run_create
    args.rsa_certificate_file)
  File "manager.py", line 114, in create_rs256_device
    return client.create_device(parent, device_template)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/cloud/iot_v1/gapic/device_manager_client.py", line 715, in create_device
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.PermissionDenied: 403 The caller does not have permission
```

I'm guessing it's related to the update of "google-auth" package?

**Comment by busunkim96** [comment]
Hi - can you double-check that your service account still has permissions to the project?

If that doesn't work, would you mind trying google-auth==1.17.2` in `requirements.txt`? If it works with the older auth lib version this is likely a bug that needs to be moved to the google-auth issue tracker.

**Comment by KKKKKyle** [comment]
Big Oops, sorry about this dumb error. I just realized I confused myself by using an older version of the service account json key (by using same naming 😢). Thanks for helping out!
