### ISSUE TITLE
asset/cloud-client test failed with AssertionError

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#4159]
[Build](https://source.cloud.google.com/results/invocations/81fad7f1-a6cd-41da-8764-a483a07bcfd9/targets)

Log:
```
Traceback (most recent call last):
  File "/workspace/asset/cloud-client/quickstart_searchallresources_test.py", line 64, in test_search_all_resources
    eventually_consistent_test()
  File "/workspace/asset/cloud-client/.nox/py-3-6/lib/python3.6/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/workspace/asset/cloud-client/quickstart_searchallresources_test.py", line 62, in eventually_consistent_test
    assert DATASET in out
AssertionError: assert 'dataset_177adbe07e3b45e49d3957d508a2e87e' in ''
```

**Comment by tmatsuo** [comment]
covered by #4164
