### ISSUE TITLE
Test failures in dataflow/flex-templates/streaming_beam

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#4459]
Failures:

[py-3.6 build](https://source.cloud.google.com/results/invocations/df87f819-2b8c-457e-b8bc-7447617e0471/targets)
[py-3.7 build](https://source.cloud.google.com/results/invocations/7cc7af55-23b3-44bb-a99d-e2c103c31f42/targets)

Log for py-3.6:
```
Traceback (most recent call last):
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "{"created":"@1596791602.912325450","description":"Error received from peer ipv4:74.125.195.95:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Stream removed","grpc_status":2}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/dataflow/flex-templates/streaming_beam/streaming_beam_test.py", line 56, in subscription_path
    subscriber.delete_subscription(subscription_path)
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/google/cloud/pubsub_v1/gapic/subscriber_client.py", line 745, in delete_subscription
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/workspace/dataflow/flex-templates/streaming_beam/.nox/py-3-6/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unknown: None Stream removed
```

The same test failed in [another build](https://source.cloud.google.com/results/invocations/7cc7af55-23b3-44bb-a99d-e2c103c31f42/targets)

**Comment by davidcavazos** [comment]
I'll take a closer look, but it might be a dependency version incompatibility

**Comment by tmatsuo** [comment]
Now it's tracked in #4492
