### ISSUE TITLE
scheduled exports frequently fail with Broken Pipe error

### ISSUE THREAD

**Issue by ubragg** [GoogleCloudPlatform/python-docs-samples#4639]
## In which file did you encounter the issue?

datastore/schedule-export/main.py

### Did you change the file? If so, how?

No, I used it exactly as is.

## Describe the issue

I have implemented periodic backups for my App Engine Datastore following the instructions posted at https://cloud.google.com/datastore/docs/schedule-export

I have my backups scheduled once a day, and in the 12 days I've had it running, 3 of those 12 days have failed with the following stack trace:
```Traceback (most recent call last):
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 402, in run_background_function
    _function_handler.invoke_user_function(event_object)
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 222, in invoke_user_function
    return call_user_function(request_or_event)
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 219, in call_user_function
    event_context.Context(**request_or_event.context))
  File "/user_code/main.py", line 56, in datastore_export
    response = export_request.execute()
  File "/env/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/env/local/lib/python3.7/site-packages/googleapiclient/http.py", line 901, in execute
    headers=self.headers,
  File "/env/local/lib/python3.7/site-packages/googleapiclient/http.py", line 204, in _retry_request
    raise exception
  File "/env/local/lib/python3.7/site-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/env/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 201, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "/env/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1994, in request
    cachekey,
  File "/env/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "/env/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1558, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
  File "/opt/python3.7/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/opt/python3.7/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

This may not be an issue with the sample code, but since that's all I'm using, I figured at least you could redirect me to the right place to see if there is anything I can do to make these backups more reliable, as a 25% failure rate seems absurdly high.

**Comment by busunkim96** [comment]
@crwilcox @chrisrossi It looks like [this page](https://cloud.google.com/datastore/docs/schedule-export) recommends using datastore via `google-api-python-client`. Is `google-cloud-datastore` not an option in App Engine? I assume it would be more reliable.

**Comment by crwilcox** [comment]
@busunkim96 this may be due to the caching layer, not so much datastore. The discovery api supports a memory caching layer, but a similar interface doesn't exist, to my knowledge, in `google-cloud-datastore`.

If the caching wasn't needed then I think you could use `google-cloud-datastore`

cc: @andrewsg

**Comment by crwilcox** [comment]
I am considering this a documentation change. We likely should modify https://cloud.google.com/datastore/docs/schedule-export to instead use google-cloud-datastore

**Comment by meredithslota** [comment]
Agreed with @crwilcox's assessment; the documentation and code samples need to be updated to point users in the right direction. Assigning to @dmahugh to consider in the future (and converted the issue type to be `type: docs` to reflect this).

**Comment by meredithslota** [comment]
Reassigning to @kolea2 — candidate for @Mariatta?

**Comment by Mariatta** [comment]
Sample doc has been updated to make use of google-cloud-datastore:
https://cloud.devsite.corp.google.com/datastore/docs/schedule-export
