### ISSUE TITLE
 requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [GoogleCloudPlatform/python-docs-samples#5065]
Hi
My jobs get killed on GKE due to this error 

> Traceback (most recent call last):
  File "finetune_t5_trainer.py", line 293, in <module>
    main()
  File "finetune_t5_trainer.py", line 208, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/workdir/seq2seq/trainers/trainer.py", line 812, in train
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)
  File "/workdir/seq2seq/trainers/trainer.py", line 880, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/workdir/seq2seq/trainers/t5_trainer.py", line 316, in _save_checkpoint
    upload(self.args.output_dir, self.args.gcs_bucket)
  File "/workdir/seq2seq/utils/utils.py", line 44, in upload
    blob.upload_from_file(f)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/blob.py", line 2242, in upload_from_file
    checksum=checksum,
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/blob.py", line 2089, in _do_upload
    checksum=checksum,
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/blob.py", line 1956, in _do_resumable_upload
    response = upload.transmit_next_chunk(transport, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/resumable_media/requests/upload.py", line 503, in transmit_next_chunk
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/google/resumable_media/requests/_request_helpers.py", line 136, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "/usr/local/lib/python3.6/dist-packages/google/resumable_media/_helpers.py", line 165, in wait_and_retry
    response = func()
  File "/usr/local/lib/python3.6/dist-packages/google/auth/transport/requests.py", line 470, in request
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))

This is really crucual for me to fix, all of my jobs are failing because of this
could you help please?
thanks

**Comment by rabeehkarimimahabadi** [comment]
I can share you the codes internally also to reproduce, but the issue is that some of the files are large and this fails.

**Comment by frankyn** [comment]
Hi @rabeehkarimimahabadi,

Could you share an example code for your use-case?

cc: @andrewsg

**Comment by frankyn** [comment]
Hi @rabeehkarimimahabadi,

Reproduction steps aren't clear and happy to reopen if you have sample code. Thank you.
