### ISSUE TITLE
Flake in healthcare/api-client/v1beta1/fhir

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#5331]
[Build](https://source.cloud.google.com/results/invocations/18e86ab2-ed1e-4f38-a54a-0c3f0fb1bfe4/targets)

fhir_resources_test.test_create_patient
Details: "dataset not initialized"

Also, another flake in [another build](https://source.cloud.google.com/results/invocations/d737178d-eb4c-4a57-b175-22459fe20d05/targets):
```
________________________ test_create_delete_fhir_store _________________________
Traceback (most recent call last):
  File "/workspace/healthcare/api-client/v1beta1/fhir/fhir_stores_test.py", line 69, in test_create_delete_fhir_store
    create()
  File "/workspace/healthcare/api-client/v1beta1/fhir/.nox/py-3-6/lib/python3.6/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/workspace/healthcare/api-client/v1beta1/fhir/fhir_stores_test.py", line 67, in create
    service_account_json, project_id, cloud_region, dataset_id, fhir_store_id
  File "/workspace/healthcare/api-client/v1beta1/fhir/fhir_stores.py", line 119, in create_fhir_store
    response = request.execute()
  File "/workspace/healthcare/api-client/v1beta1/fhir/.nox/py-3-6/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/workspace/healthcare/api-client/v1beta1/fhir/.nox/py-3-6/lib/python3.6/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://healthcare.googleapis.com/v1beta1/projects/python-docs-samples-tests/locations/us-central1/datasets/test_dataset_ba9c00a2-91c4-4510-a66e-e4a7fae64fd0/fhirStores?fhirStoreId=test_fhir_store-9d653f45-4837-4118-bc15-bb08b1a10e0e&alt=json returned "dataset not initialized". Details: "dataset not initialized">
```

**Comment by tmatsuo** [comment]
Haven't seen for a while. Let's start a conversation with the product team when we see this again.
