### ISSUE TITLE
Building dlib library fails due to missing cmake

### ISSUE THREAD

**Issue by codinghedgehog-python** [GoogleCloudPlatform/python-docs-samples#5702]
I'm using the samples to deploy my Flask app on gCloud. My app is using the dlib library and when I build
the app with `gcloud app deploy` app starts to build fine (using Python 3.6 which surprised me when Python 3.9 is already around)
problem occurs when the installation process starts to build dlib's wheels. It fails on allegedly missing cmake:

```
BUILD
Starting Step #0
Step #0: Pulling image: gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #0: sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa: Pulling from gcp-runtimes/python/gen-dockerfile
Step #0: Digest: sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #0: Status: Downloaded newer image for gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #0: gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Finished Step #0
Starting Step #1
Step #1: Pulling image: gcr.io/cloud-builders/docker@sha256:fb864d4f2bc3b4642a77cfb96adab6c449b2592ba6d41db388c171134b12b275
Step #1: sha256:fb864d4f2bc3b4642a77cfb96adab6c449b2592ba6d41db388c171134b12b275: Pulling from cloud-builders/docker
Step #1: 75f546e73d8b: Already exists
Step #1: 0f3bb76fc390: Already exists
Step #1: 3c2cba919283: Already exists
Step #1: ea4bb9fa6007: Pulling fs layer
Step #1: 33f2cb8e56da: Pulling fs layer
Step #1: 33f2cb8e56da: Verifying Checksum
Step #1: 33f2cb8e56da: Download complete
Step #1: ea4bb9fa6007: Verifying Checksum
Step #1: ea4bb9fa6007: Download complete
Step #1: ea4bb9fa6007: Pull complete
Step #1: 33f2cb8e56da: Pull complete
Step #1: Digest: sha256:fb864d4f2bc3b4642a77cfb96adab6c449b2592ba6d41db388c171134b12b275
Step #1: Status: Downloaded newer image for gcr.io/cloud-builders/docker@sha256:fb864d4f2bc3b4642a77cfb96adab6c449b2592ba6d41db388c171134b12b275
Step #1: gcr.io/cloud-builders/docker@sha256:fb864d4f2bc3b4642a77cfb96adab6c449b2592ba6d41db388c171134b12b275
Step #1: Sending build context to Docker daemon  1.052MB
Step #1: Step 1/9 : FROM gcr.io/google-appengine/python@sha256:fc9d9f429bf75b8369f7894b7eb24098418050557b889f4b02aa4c93fdb5e161
Step #1: sha256:fc9d9f429bf75b8369f7894b7eb24098418050557b889f4b02aa4c93fdb5e161: Pulling from google-appengine/python
Step #1: Digest: sha256:fc9d9f429bf75b8369f7894b7eb24098418050557b889f4b02aa4c93fdb5e161
Step #1: Status: Downloaded newer image for gcr.io/google-appengine/python@sha256:fc9d9f429bf75b8369f7894b7eb24098418050557b889f4b02aa4c93fdb5e161
Step #1:  ---> 96b4d9af6594
Step #1: Step 2/9 : LABEL python_version=python3.6
Step #1:  ---> Running in 84ae393daa19
Step #1: Removing intermediate container 84ae393daa19
Step #1:  ---> c54a51a6f17d
Step #1: Step 3/9 : RUN virtualenv --no-download /env -p python3.6
Step #1:  ---> Running in 7d17deb94a4c
Step #1: created virtual environment CPython3.6.10.final.0-64 in 1038ms
Step #1:   creator CPython3Posix(dest=/env, clear=False, global=False)
Step #1:   seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
Step #1:     added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
Step #1:   activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
Step #1: Removing intermediate container 7d17deb94a4c
Step #1:  ---> 01619b263761
Step #1: Step 4/9 : ENV VIRTUAL_ENV /env
Step #1:  ---> Running in 00f060b28297
Step #1: Removing intermediate container 00f060b28297
Step #1:  ---> ef72eb4d8e2e
Step #1: Step 5/9 : ENV PATH /env/bin:$PATH
Step #1:  ---> Running in 3e53b31d97e6
Step #1: Removing intermediate container 3e53b31d97e6
Step #1:  ---> 53b85ea710ba
Step #1: Step 6/9 : ADD requirements.txt /app/
Step #1:  ---> 6d75619cdbff
Step #1: Step 7/9 : RUN pip install -r requirements.txt
Step #1:  ---> Running in 47731e202c96
Step #1: Collecting Flask==1.1.2
Step #1:   Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Step #1: Collecting Flask-MySQLdb==0.2.0
Step #1:   Downloading Flask-MySQLdb-0.2.0.tar.gz (2.1 kB)
Step #1: Collecting Flask-SQLAlchemy==2.4.4
Step #1:   Downloading Flask_SQLAlchemy-2.4.4-py2.py3-none-any.whl (17 kB)
Step #1: Collecting Flask-Login==0.5.0
Step #1:   Downloading Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB)
Step #1: Collecting Flask-Debugtoolbar==0.11.0
Step #1:   Downloading Flask_DebugToolbar-0.11.0-py2.py3-none-any.whl (325 kB)
Step #1: Collecting Flask-Admin==1.5.7
Step #1:   Downloading Flask-Admin-1.5.7.tar.gz (6.6 MB)
Step #1: Collecting Flask-CORS==3.0.10
Step #1:   Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Step #1: Collecting Flask-Bcrypt==0.7.1
Step #1:   Downloading Flask-Bcrypt-0.7.1.tar.gz (5.1 kB)
Step #1: Collecting mysql-connector-python==8.0.23
Step #1:   Downloading mysql_connector_python-8.0.23-cp36-cp36m-manylinux1_x86_64.whl (18.0 MB)
Step #1: Collecting Pytest==6.2.2
Step #1:   Downloading pytest-6.2.2-py3-none-any.whl (280 kB)
Step #1: Collecting Faker==6.5.0
Step #1:   Downloading Faker-6.5.0-py3-none-any.whl (1.1 MB)
Step #1: Collecting awesome-slugify==1.6.5
Step #1:   Downloading awesome-slugify-1.6.5.tar.gz (8.4 kB)
Step #1: Collecting pytesseract==0.3.6
Step #1:   Downloading pytesseract-0.3.6.tar.gz (13 kB)
Step #1: Collecting Pillow==8.0.0
Step #1:   Downloading Pillow-8.0.0-cp36-cp36m-manylinux1_x86_64.whl (2.2 MB)
Step #1: Collecting opencv-python-headless==4.4.0.46
Step #1:   Downloading opencv_python_headless-4.4.0.46-cp36-cp36m-manylinux2014_x86_64.whl (36.7 MB)
Step #1: Collecting dlib==19.21.0
Step #1:   Downloading dlib-19.21.0.tar.gz (3.2 MB)
Step #1: Collecting face-recognition==1.3.0
Step #1:   Downloading face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)
Step #1: Collecting requests==2.22.0
Step #1:   Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
Step #1: Collecting gunicorn==20.1.0
Step #1:   Downloading gunicorn-20.1.0.tar.gz (370 kB)
Step #1: Collecting google-cloud-storage==1.37.1
Step #1:   Downloading google_cloud_storage-1.37.1-py2.py3-none-any.whl (103 kB)
Step #1: Collecting Jinja2>=2.10.1
Step #1:   Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Step #1: Collecting itsdangerous>=0.24
Step #1:   Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Step #1: Collecting click>=5.1
Step #1:   Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Step #1: Collecting Werkzeug>=0.15
Step #1:   Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Step #1: Collecting mysqlclient
Step #1:   Downloading mysqlclient-2.0.3.tar.gz (88 kB)
Step #1: Collecting SQLAlchemy>=0.8.0
Step #1:   Downloading SQLAlchemy-1.4.8-cp36-cp36m-manylinux2014_x86_64.whl (1.5 MB)
Step #1: Collecting Blinker
Step #1:   Downloading blinker-1.4.tar.gz (111 kB)
Step #1: Collecting wtforms
Step #1:   Downloading WTForms-2.3.3-py2.py3-none-any.whl (169 kB)
Step #1: Collecting Six
Step #1:   Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Step #1: Collecting bcrypt
Step #1:   Downloading bcrypt-3.2.0-cp36-abi3-manylinux2010_x86_64.whl (63 kB)
Step #1: Collecting protobuf>=3.0.0
Step #1:   Downloading protobuf-3.15.8-cp36-cp36m-manylinux1_x86_64.whl (1.0 MB)
Step #1: Collecting toml
Step #1:   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Step #1: Collecting importlib-metadata>=0.12; python_version < "3.8"
Step #1:   Downloading importlib_metadata-3.10.1-py3-none-any.whl (14 kB)
Step #1: Collecting iniconfig
Step #1:   Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Step #1: Collecting attrs>=19.2.0
Step #1:   Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Step #1: Collecting py>=1.8.2
Step #1:   Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)
Step #1: Collecting pluggy<1.0.0a1,>=0.12
Step #1:   Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Step #1: Collecting packaging
Step #1:   Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
Step #1: Collecting python-dateutil>=2.4
Step #1:   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Step #1: Collecting text-unidecode==1.3
Step #1:   Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Step #1: Collecting regex
Step #1:   Downloading regex-2021.4.4-cp36-cp36m-manylinux2014_x86_64.whl (722 kB)
Step #1: Collecting Unidecode<0.05,>=0.04.14
Step #1:   Downloading Unidecode-0.04.21-py2.py3-none-any.whl (228 kB)
Step #1: Collecting numpy>=1.13.3
Step #1:   Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Step #1: Collecting face-recognition-models>=0.3.0
Step #1:   Downloading face_recognition_models-0.3.0.tar.gz (100.1 MB)
Step #1: Collecting idna<2.9,>=2.5
Step #1:   Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
Step #1: Collecting certifi>=2017.4.17
Step #1:   Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Step #1: Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
Step #1:   Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Step #1: Collecting chardet<3.1.0,>=3.0.2
Step #1:   Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Step #1: Requirement already satisfied: setuptools>=3.0 in /env/lib/python3.6/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 19)) (49.6.0)
Step #1: Collecting google-auth<2.0dev,>=1.11.0
Step #1:   Downloading google_auth-1.28.1-py2.py3-none-any.whl (136 kB)
Step #1: Collecting google-cloud-core<2.0dev,>=1.4.1
Step #1:   Downloading google_cloud_core-1.6.0-py2.py3-none-any.whl (28 kB)
Step #1: Collecting google-resumable-media<2.0dev,>=1.2.0
Step #1:   Downloading google_resumable_media-1.2.0-py2.py3-none-any.whl (75 kB)
Step #1: Collecting MarkupSafe>=0.23
Step #1:   Downloading MarkupSafe-1.1.1-cp36-cp36m-manylinux2010_x86_64.whl (32 kB)
Step #1: Collecting greenlet!=0.4.17; python_version >= "3"
Step #1:   Downloading greenlet-1.0.0-cp36-cp36m-manylinux2010_x86_64.whl (156 kB)
Step #1: Collecting cffi>=1.1
Step #1:   Downloading cffi-1.14.5-cp36-cp36m-manylinux1_x86_64.whl (401 kB)
Step #1: Collecting typing-extensions>=3.6.4; python_version < "3.8"
Step #1:   Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Step #1: Collecting zipp>=0.5
Step #1:   Downloading zipp-3.4.1-py3-none-any.whl (5.2 kB)
Step #1: Collecting pyparsing>=2.0.2
Step #1:   Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Step #1: Collecting pyasn1-modules>=0.2.1
Step #1:   Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Step #1: Collecting cachetools<5.0,>=2.0.0
Step #1:   Downloading cachetools-4.2.1-py3-none-any.whl (12 kB)
Step #1: Collecting rsa<5,>=3.1.4; python_version >= "3.6"
Step #1:   Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Step #1: Collecting google-api-core<2.0.0dev,>=1.21.0
Step #1:   Downloading google_api_core-1.26.3-py2.py3-none-any.whl (93 kB)
Step #1: Collecting google-crc32c<2.0dev,>=1.0; python_version >= "3.5"
Step #1:   Downloading google_crc32c-1.1.2-cp36-cp36m-manylinux2014_x86_64.whl (38 kB)
Step #1: Collecting pycparser
Step #1:   Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Step #1: Collecting pyasn1<0.5.0,>=0.4.6
Step #1:   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Step #1: Collecting pytz
Step #1:   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
Step #1: Collecting googleapis-common-protos<2.0dev,>=1.6.0
Step #1:   Downloading googleapis_common_protos-1.53.0-py2.py3-none-any.whl (198 kB)
Step #1: Building wheels for collected packages: Flask-MySQLdb, Flask-Admin, Flask-Bcrypt, awesome-slugify, pytesseract, dlib, gunicorn, mysqlclient, Blinker, face-recognition-models
Step #1:   Building wheel for Flask-MySQLdb (setup.py): started
Step #1:   Building wheel for Flask-MySQLdb (setup.py): finished with status 'done'
Step #1:   Created wheel for Flask-MySQLdb: filename=Flask_MySQLdb-0.2.0-py3-none-any.whl size=2667 sha256=75cca410aaeb9afebbb035c918d0d26ca0eb8588ce02727a56b45d2739b487aa
Step #1:   Stored in directory: /root/.cache/pip/wheels/56/e8/13/f56acc8e609a558e5c6f9ae745ccd9843795ca0e6a3fc019d8
Step #1:   Building wheel for Flask-Admin (setup.py): started
Step #1:   Building wheel for Flask-Admin (setup.py): finished with status 'done'
Step #1:   Created wheel for Flask-Admin: filename=Flask_Admin-1.5.7-py3-none-any.whl size=7492406 sha256=106746118857ccf3c92c9c739bbf10045d32c1b835a87eeb6acd67d99806277b
Step #1:   Stored in directory: /root/.cache/pip/wheels/fa/56/ad/3012811769dab0caea5f5eedfa0ddd2598a650647ff34e6adb
Step #1:   Building wheel for Flask-Bcrypt (setup.py): started
Step #1:   Building wheel for Flask-Bcrypt (setup.py): finished with status 'done'
Step #1:   Created wheel for Flask-Bcrypt: filename=Flask_Bcrypt-0.7.1-py3-none-any.whl size=5011 sha256=37a2c69beb3f6b2e6c5e3c0cfbbdf3279a7a0833dd2781737d056408ed1d1045
Step #1:   Stored in directory: /root/.cache/pip/wheels/c9/5c/81/9da99305abd85cb148b6428bd1a8e37aff10908430b0e2474a
Step #1:   Building wheel for awesome-slugify (setup.py): started
Step #1:   Building wheel for awesome-slugify (setup.py): finished with status 'done'
Step #1:   Created wheel for awesome-slugify: filename=awesome_slugify-1.6.5-py3-none-any.whl size=8354 sha256=f751b299b2cd843f0d2b2b02867339b4004100756e218991a50c7f8d42f9c67e
Step #1:   Stored in directory: /root/.cache/pip/wheels/e0/86/b4/7050d46dc9f8650d2f39d3203c044f289fb286b571e518178f
Step #1:   Building wheel for pytesseract (setup.py): started
Step #1:   Building wheel for pytesseract (setup.py): finished with status 'done'
Step #1:   Created wheel for pytesseract: filename=pytesseract-0.3.6-py2.py3-none-any.whl size=13629 sha256=8ed17f3373d203ee47af5e3cf7815d0513cc083f01d46e4c27a84d97f9da4c49
Step #1:   Stored in directory: /root/.cache/pip/wheels/61/1a/34/93d256a3b4c6b1d2c08cc2b17b1502af8c5b320eac5eaec1f6
Step #1:   Building wheel for dlib (setup.py): started
Step #1:   Building wheel for dlib (setup.py): finished with status 'error'
Step #1:   ERROR: Command errored out with exit status 1:
Step #1:    command: /env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3p1noqkw/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3p1noqkw/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-iqlflpki
Step #1:        cwd: /tmp/pip-install-3p1noqkw/dlib/
Step #1:   Complete output (53 lines):
Step #1:   running bdist_wheel
Step #1:   running build
Step #1:   running build_py
Step #1:   package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
Step #1:   running build_ext
Step #1:   Traceback (most recent call last):
Step #1:     File "/tmp/pip-install-3p1noqkw/dlib/setup.py", line 120, in get_cmake_version
Step #1:       out = subprocess.check_output(['cmake', '--version'])
Step #1:     File "/opt/python3.6/lib/python3.6/subprocess.py", line 356, in check_output
Step #1:       **kwargs).stdout
Step #1:     File "/opt/python3.6/lib/python3.6/subprocess.py", line 423, in run
Step #1:       with Popen(*popenargs, **kwargs) as process:
Step #1:     File "/opt/python3.6/lib/python3.6/subprocess.py", line 729, in __init__
Step #1:       restore_signals, start_new_session)
Step #1:     File "/opt/python3.6/lib/python3.6/subprocess.py", line 1364, in _execute_child
Step #1:       raise child_exception_type(errno_num, err_msg, err_filename)
Step #1:   FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
Step #1:   
Step #1:   During handling of the above exception, another exception occurred:
Step #1:   
Step #1:   Traceback (most recent call last):
Step #1:     File "<string>", line 1, in <module>
Step #1:     File "/tmp/pip-install-3p1noqkw/dlib/setup.py", line 262, in <module>
Step #1:       'Topic :: Software Development',
Step #1:     File "/env/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in setup
Step #1:       return distutils.core.setup(**attrs)
Step #1:     File "/opt/python3.6/lib/python3.6/distutils/core.py", line 148, in setup
Step #1:       dist.run_commands()
Step #1:     File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
Step #1:       self.run_command(cmd)
Step #1:     File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
Step #1:       cmd_obj.run()
Step #1:     File "/env/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
Step #1:       self.run_command('build')
Step #1:     File "/opt/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
Step #1:       self.distribution.run_command(command)
Step #1:     File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
Step #1:       cmd_obj.run()
Step #1:     File "/opt/python3.6/lib/python3.6/distutils/command/build.py", line 135, in run
Step #1:       self.run_command(cmd_name)
Step #1:     File "/opt/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
Step #1:       self.distribution.run_command(command)
Step #1:     File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
Step #1:       cmd_obj.run()
Step #1:     File "/tmp/pip-install-3p1noqkw/dlib/setup.py", line 129, in run
Step #1:       cmake_version = self.get_cmake_version()
Step #1:     File "/tmp/pip-install-3p1noqkw/dlib/setup.py", line 125, in get_cmake_version
Step #1:       "\n*******************************************************************\n")
Step #1:   RuntimeError:
Step #1:   *******************************************************************
Step #1:    CMake must be installed to build the following extensions: _dlib_pybind11
Step #1:   *******************************************************************
Step #1:   
Step #1:   ----------------------------------------
Step #1:   ERROR: Failed building wheel for dlib
Step #1:   Running setup.py clean for dlib
Step #1:   Building wheel for gunicorn (setup.py): started
Step #1:   Building wheel for gunicorn (setup.py): finished with status 'done'
Step #1:   Created wheel for gunicorn: filename=gunicorn-20.1.0-py3-none-any.whl size=78918 sha256=a725453ceeb4427c6eaa8fe55bac2e98c05665535b97bbd59ca7f7b5884187f8
Step #1:   Stored in directory: /root/.cache/pip/wheels/9a/86/37/cad4bc71746b420e17c4eb0f5c41cf7b5e653c1fdbda27d198
Step #1:   Building wheel for mysqlclient (setup.py): started
Step #1:   Building wheel for mysqlclient (setup.py): finished with status 'done'
Step #1:   Created wheel for mysqlclient: filename=mysqlclient-2.0.3-cp36-cp36m-linux_x86_64.whl size=99079 sha256=845189dff75ea49ce649732a0296d65a75c2c3d2739d5a446ccb5c882dc69642
Step #1:   Stored in directory: /root/.cache/pip/wheels/26/d0/50/9ab7ee785bf3c7485d19fe645ea080478c54a16ab81c771112
Step #1:   Building wheel for Blinker (setup.py): started
Step #1:   Building wheel for Blinker (setup.py): finished with status 'done'
Step #1:   Created wheel for Blinker: filename=blinker-1.4-py3-none-any.whl size=13452 sha256=dcad7e2b4df37bec3e7185d903f3be574a04f004f3324ee2f37b0c40c46b26d6
Step #1:   Stored in directory: /root/.cache/pip/wheels/4f/4a/93/c5ed8c11fedbe97fb8b8032b301eaa736248684b44087a7259
Step #1:   Building wheel for face-recognition-models (setup.py): started
Step #1:   Building wheel for face-recognition-models (setup.py): finished with status 'done'
Step #1:   Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566173 sha256=5c42d853a87b193d03ffd8d48cb9219ecb47fae5f6f0ac60aeba8c1ca278a0b1
Step #1:   Stored in directory: /root/.cache/pip/wheels/6a/e1/1a/8969952b51c25409d5b96ecb09603de12b8534bd6d68e6e7d1
Step #1: Successfully built Flask-MySQLdb Flask-Admin Flask-Bcrypt awesome-slugify pytesseract gunicorn mysqlclient Blinker face-recognition-models
Step #1: Failed to build dlib
Step #1: DEPRECATION: Could not build wheels for dlib which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Step #1: Installing collected packages: MarkupSafe, Jinja2, itsdangerous, click, Werkzeug, Flask, mysqlclient, Flask-MySQLdb, greenlet, typing-extensions, zipp, importlib-metadata, SQLAlchemy, Flask-SQLAlchemy, Flask-Login, Blinker, Flask-Debugtoolbar, wtforms, Flask-Admin, Six, Flask-CORS, pycparser, cffi, bcrypt, Flask-Bcrypt, protobuf, mysql-connector-python, toml, iniconfig, attrs, py, pluggy, pyparsing, packaging, Pytest, python-dateutil, text-unidecode, Faker, regex, Unidecode, awesome-slugify, Pillow, pytesseract, numpy, opencv-python-headless, dlib, face-recognition-models, face-recognition, idna, certifi, urllib3, chardet, requests, gunicorn, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, pytz, googleapis-common-protos, google-api-core, google-cloud-core, google-crc32c, google-resumable-media, google-cloud-storage
Step #1:     Running setup.py install for dlib: started
Step #1:     Running setup.py install for dlib: finished with status 'error'
Step #1:     ERROR: Command errored out with exit status 1:
Step #1:      command: /env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3p1noqkw/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3p1noqkw/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6zmfc7ub/install-record.txt --single-version-externally-managed --compile --install-headers /env/include/site/python3.6/dlib
Step #1:          cwd: /tmp/pip-install-3p1noqkw/dlib/
Step #1:     Complete output (55 lines):
Step #1:     running install
Step #1:     running build
Step #1:     running build_py
Step #1:     package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
Step #1:     running build_ext
Step #1:     Traceback (most recent call last):
Step #1:       File "/tmp/pip-install-3p1noqkw/dlib/setup.py", line 120, in get_cmake_version
Step #1:         out = subprocess.check_output(['cmake', '--version'])
Step #1:       File "/opt/python3.6/lib/python3.6/subprocess.py", line 356, in check_output
Step #1:         **kwargs).stdout
Step #1:       File "/opt/python3.6/lib/python3.6/subprocess.py", line 423, in run
Step #1:         with Popen(*popenargs, **kwargs) as process:
Step #1:       File "/opt/python3.6/lib/python3.6/subprocess.py", line 729, in __init__
Step #1:         restore_signals, start_new_session)
Step #1:       File "/opt/python3.6/lib/python3.6/subprocess.py", line 1364, in _execute_child
Step #1:         raise child_exception_type(errno_num, err_msg, err_filename)
Step #1:     FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
Step #1:     
Step #1:     During handling of the above exception, another exception occurred:
Step #1:     
Step #1:     Traceback (most recent call last):
Step #1:       File "<string>", line 1, in <module>
Step #1:       File "/tmp/pip-install-3p1noqkw/dlib/setup.py", line 262, in <module>
Step #1:         'Topic :: Software Development',
Step #1:       File "/env/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in setup
Step #1:         return distutils.core.setup(**attrs)
Step #1:       File "/opt/python3.6/lib/python3.6/distutils/core.py", line 148, in setup
Step #1:         dist.run_commands()
Step #1:       File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
Step #1:         self.run_command(cmd)
Step #1:       File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
Step #1:         cmd_obj.run()
Step #1:       File "/env/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
Step #1:         return orig.install.run(self)
Step #1:       File "/opt/python3.6/lib/python3.6/distutils/command/install.py", line 545, in run
Step #1:         self.run_command('build')
Step #1:       File "/opt/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
Step #1:         self.distribution.run_command(command)
Step #1:       File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
Step #1:         cmd_obj.run()
Step #1:       File "/opt/python3.6/lib/python3.6/distutils/command/build.py", line 135, in run
Step #1:         self.run_command(cmd_name)
Step #1:       File "/opt/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
Step #1:         self.distribution.run_command(command)
Step #1:       File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
Step #1:         cmd_obj.run()
Step #1:       File "/tmp/pip-install-3p1noqkw/dlib/setup.py", line 129, in run
Step #1:         cmake_version = self.get_cmake_version()
Step #1:       File "/tmp/pip-install-3p1noqkw/dlib/setup.py", line 125, in get_cmake_version
Step #1:         "\n*******************************************************************\n")
Step #1:     RuntimeError:
Step #1:     *******************************************************************
Step #1:      CMake must be installed to build the following extensions: _dlib_pybind11
```
I checked and cmake is installed system-wide in the ephemeral environment but apparently cmake isn't present when container environment is created.

Any feedback is much appreciated.

**Comment by dandhlee** [comment]
Hey there! I can't really pinpoint to which sample you seem to be having an issue, could you clarify which files / samples you're having this issue with?

**Comment by codinghedgehog-python** [comment]
To be fair I don't think the problem is with sample files but rather the environment that it is meant for. I apologize if this issue tracker isn't the right place to put this in. I'm using the "hello-world" sample files which are a boilerplate for Flask app. I edited the directory to suit my needs and `cmake` isn't present in the container environment that gets created when I run `gcloud app deploy`.
Once again I suspect this is rather environment issue since I've seen a tutorial on YouTube where the deployment works just fine but if you need to install the `dlib` library you may run into issue with `cmake`.

**Comment by dandhlee** [comment]
Ah I see. If it's not samples in this repo's issue then I'm afraid there's nothing much the Samples folks here can do. If you're following any of our tutorials hosted on the getting started page for GCP I can take a look and relay your concerns to the team! 

If the YouTube video is one of our walkthroughs and/or if you've been also referring to any of our walkthrough/tutorials/guides, feel free to share it here so I can try help out as much as I can.
