### ISSUE TITLE
Error while using this script from Google Cloud API

### ISSUE THREAD

**Issue by baditaflorin** [GoogleCloudPlatform/python-docs-samples#683]
## In which file did you encounter the issue?
analyze.py

### Did you change the file? If so, how?
No

## Describe the issue
python analyze.py entities "John is late"

Traceback (most recent call last):
  File "analyze.py", line 103, in <module>
    result = analyze_entities(args.text, get_native_encoding_type())
  File "analyze.py", line 53, in analyze_entities
    response = request.execute()
  File "/home/florinb/python-docs-samples/language/env/local/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/florinb/python-docs-samples/language/env/local/lib/python2.7/site-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://language.googleapis.com/v1/documents:analyzeEntities?alt=json returned "Request had insufficient authentication scopes.">

**Comment by jonparrott** [comment]
@puneith or @jerjou any ideas?

**Comment by jerjou** [comment]
Hello!

Thanks for the bug report. Are you running the latest version of the code? I can't be sure because you didn't provide the full path to the `analyze.py` that you ran, but from the looks of your stack trace, since you're running from a virtualenv in the `language/` directory, I'm guessing you're running the file `language/analyze.py`. Note that the latest version of `analyze.py` is in the directory `language/api/`.

Try pulling down the latest version of the code:

    cd ~/python-docs-samples/
    git pull origin

and running it again:

    export GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/credentials.json
    cd language/api/
    python analyze.py -h
    python analyze.py syntax "John is late"

**Comment by puneith** [comment]
@baditaflorin Did it work for you?

**Comment by gguuss** [comment]
@baditaflorin - I see that you are getting **HTTP 403** error codes. You need to [Enable the speech API in your Cloud API Project](https://cloud.google.com/natural-language/docs/getting-started#set_up_your_project) and set the **GOOGLE_APPLICATION_CREDENTIAL** environment variable to the service account credentials that you downloaded when you set up the project.

**Comment by jerjou** [comment]
Closing due to inactivity. Please comment with an update if you're still getting this error, and we can reopen.
