### ISSUE TITLE
airflow_db_cleanup fails on TaskInstance and TaskReschedule tables in Composer 2.x

### ISSUE THREAD

**Issue by shane-graham** [GoogleCloudPlatform/python-docs-samples#7835]
## In which file did you encounter the issue?

composer/workflows/airflow_db_cleanup.py

### Did you change the file? If so, how?

No changes to the file, other than making the default for airflow_db_cleanup__max_db_entry_age_in_days 90 days.  

## Describe the issue

When allowing the DAG to execute per the schedule, all of the tables are processed except for TaskInstance and TaskReschedule which produce the following error:

[2022-04-26, 14:51:42 UTC] {airflow_db_cleanup_v1.py:292} INFO - Running Cleanup Process...
[2022-04-26, 14:51:42 UTC] {taskinstance.py:1702} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1330, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1457, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1513, in _execute_task
    result = execute_callable(context=context)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/gcs/dags/airflow_db_cleanup_v1.py", line 295, in cleanup_function
    query = session.query(airflow_db_model).options(
  File "/opt/python3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1619, in options
    return self._options(False, *args)
  File "<string>", line 2, in _options
  File "/opt/python3.8/lib/python3.8/site-packages/sqlalchemy/orm/base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "/opt/python3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1638, in _options
    opt.process_query(self)
  File "/opt/python3.8/lib/python3.8/site-packages/sqlalchemy/orm/strategy_options.py", line 176, in process_query
    self._process(query, True)
  File "/opt/python3.8/lib/python3.8/site-packages/sqlalchemy/orm/strategy_options.py", line 677, in _process
    val._bind_loader(
  File "/opt/python3.8/lib/python3.8/site-packages/sqlalchemy/orm/strategy_options.py", line 829, in _bind_loader
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: mapper option expects string key or list of attributes

Googling for the `sqlalchemy.exc.ArgumentError: mapper option expects string key or list of attributes` didn't help me, but I admit I'm not versed in SQLAlchemy, so I'll try this issue.

When we were using Airflow 1.x/Composer 1.x this version of the script worked:  [airflow_db_cleanup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/composer/airflow_1_samples/airflow_db_cleanup.py)

**Comment by mhenc** [comment]
You need to change
```
        "age_check_column": TaskReschedule.execution_date,
```
to
```

**Comment by mhenc** [comment]
You need to change
```
"age_check_column": TaskReschedule.execution_date,
```
to
```
"age_check_column": TaskReschedule.run_id,
```
and
```
"age_check_column": TaskReschedule.execution_date,
```
to
```
"age_check_column": TaskReschedule.run_id,
```

Seems the filed was renamed in https://github.com/apache/airflow/pull/17719

We will prepare a fix

**Comment by shane-graham** [comment]
Great!  Thanks for looking into it.

**Comment by shane-graham** [comment]
The tasks no longer fail with the fix, however I'm don't think any data is getting removed based on the following log entry for the TaskInstance task:

[2022-04-29, 15:01:17 EDT] {airflow_db_cleanup_v1.py:282} INFO - Retrieving max_execution_date from XCom
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:294} INFO - Configurations:
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:295} INFO - max_date:                 2021-10-31 19:01:08.416569+00:00
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:296} INFO - enable_delete:            True
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:297} INFO - session:                  <sqlalchemy.orm.session.Session object at 0x7f213a78c8b0>
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:298} INFO - airflow_db_model:         <class 'airflow.models.taskinstance.TaskInstance'>
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:299} INFO - state:                    None
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:300} INFO - age_check_column:         TaskInstance.run_id
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:301} INFO - keep_last:                False
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:302} INFO - keep_last_filters:        None
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:303} INFO - keep_last_group_by:       None
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:305} INFO - 
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:307} INFO - Running Cleanup Process...
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:313} INFO - INITIAL QUERY : SELECT task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, task_instance.run_id AS task_instance_run_id, dag_run_1.state AS dag_run_1_state, dag_run_1.id AS dag_run_1_id, dag_run_1.dag_id AS dag_run_1_dag_id, dag_run_1.queued_at AS dag_run_1_queued_at, dag_run_1.execution_date AS dag_run_1_execution_date, dag_run_1.start_date AS dag_run_1_start_date, dag_run_1.end_date AS dag_run_1_end_date, dag_run_1.run_id AS dag_run_1_run_id, dag_run_1.creating_job_id AS dag_run_1_creating_job_id, dag_run_1.external_trigger AS dag_run_1_external_trigger, dag_run_1.run_type AS dag_run_1_run_type, dag_run_1.conf AS dag_run_1_conf, dag_run_1.data_interval_start AS dag_run_1_data_interval_start, dag_run_1.data_interval_end AS dag_run_1_data_interval_end, dag_run_1.last_scheduling_decision AS dag_run_1_last_scheduling_decision, dag_run_1.dag_hash AS dag_run_1_dag_hash 
FROM task_instance JOIN dag_run AS dag_run_1 ON dag_run_1.dag_id = task_instance.dag_id AND dag_run_1.run_id = task_instance.run_id
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:372} ERROR - (psycopg2.errors.UndefinedFunction) operator does not exist: character varying <= timestamp with time zone
LINE 3: WHERE task_instance.run_id <= '2021-10-31T19:01:08.416569+00...
                                   ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, task_instance.run_id AS task_instance_run_id, dag_run_1.state AS dag_run_1_state, dag_run_1.id AS dag_run_1_id, dag_run_1.dag_id AS dag_run_1_dag_id, dag_run_1.queued_at AS dag_run_1_queued_at, dag_run_1.execution_date AS dag_run_1_execution_date, dag_run_1.start_date AS dag_run_1_start_date, dag_run_1.end_date AS dag_run_1_end_date, dag_run_1.run_id AS dag_run_1_run_id, dag_run_1.creating_job_id AS dag_run_1_creating_job_id, dag_run_1.external_trigger AS dag_run_1_external_trigger, dag_run_1.run_type AS dag_run_1_run_type, dag_run_1.conf AS dag_run_1_conf, dag_run_1.data_interval_start AS dag_run_1_data_interval_start, dag_run_1.data_interval_end AS dag_run_1_data_interval_end, dag_run_1.last_scheduling_decision AS dag_run_1_last_scheduling_decision, dag_run_1.dag_hash AS dag_run_1_dag_hash 
FROM task_instance JOIN dag_run AS dag_run_1 ON dag_run_1.dag_id = task_instance.dag_id AND dag_run_1.run_id = task_instance.run_id 
WHERE task_instance.run_id <= %(run_id_1)s]
[parameters: {'run_id_1': datetime.datetime(2021, 10, 31, 19, 1, 8, 416569, tzinfo=tzlocal())}]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2022-04-29, 15:01:18 EDT] {airflow_db_cleanup_v1.py:373} ERROR - <class 'airflow.models.taskinstance.TaskInstance'> is not present in the metadata.Skipping...
[2022-04-29, 15:01:18 EDT] {python.py:175} INFO - Done. Returned value was: None
[2022-04-29, 15:01:20 EDT] {taskinstance.py:1268} INFO - Marking task as SUCCESS. dag_id=airflow_db_cleanup_v1, task_id=cleanup_TaskInstance, execution_date=20220428T000000, start_date=20220429T190114, end_date=20220429T190120
[2022-04-29, 15:01:21 EDT] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29, 15:01:21 EDT] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check

**Comment by atulep** [comment]
@mhenc Can you take another look ?

**Comment by shane-graham** [comment]
May I ask what the workaround entails?

**Comment by parthea** [comment]
The workaround is to apply the changes from https://github.com/GoogleCloudPlatform/python-docs-samples/pull/7847/files. From https://github.com/GoogleCloudPlatform/python-docs-samples/issues/7835#issuecomment-1113634818, it sounds like additional changes are needed in #7847. I'll add the p1 label back and add a comment in the PR.

**Comment by khokharnikunj8** [comment]
Thanks @parthea for finding the bug. I've updated the script accordingly. Thanks!
