### ISSUE TITLE
Cannot run datastore/cloud-client/snippets.py

### ISSUE THREAD

**Issue by jlara310** [GoogleCloudPlatform/python-docs-samples#7900]
## In which file did you encounter the issue?

[python-docs-samples/blob/main/datastore/cloud-client/snippets.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/datastore/cloud-client/snippets.py)

### Did you change the file? If so, how?
No changes.

## Describe the issue

Cannot run this file as expected:

` python3 snippets.py <project-id>`

Error returned:

```
Traceback (most recent call last):
  File "/upython-docs-samples/datastore/cloud-client/snippets.py", line 1011, in <module>
    main(args.project_id)
  File "python-docs-samples/datastore/cloud-client/snippets.py", line 994, in main
    for name, function in globals().iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
````

Updating `main` as follows got it to work:

```
def main(project_id):
    client = datastore.Client(project_id)

    for name, function in list(globals().items()):
        if name in ("main", "_preamble", "defaultdict") or not callable(function):
            continue

        print(name)
        pprint(function(client))
        print("\n-----------------\n")
```

**Comment by kurtisvg** [comment]
Change seems reasonable to me.
