### ISSUE TITLE
Why is there no dropdown to select an existing Google Cloud project in the create Firebase project page?

### ISSUE THREAD

**Issue by mycar98765** [GoogleCloudPlatform/python-docs-samples#8433]
I'm creating a Python project and getting data from Google Cloud Firestore, **not** Firebase Cloud Firestore.

When I run it, I get the following error:

    Traceback (most recent call last):
      File "main.py", line 17, in <module>
        for doc in docs:
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/cloud/firestore_v1/query.py", line 276, in stream
        timeout,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/cloud/firestore_v1/query.py", line 221, in _get_stream_iterator
        **kwargs,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/cloud/firestore_v1/services/firestore/client.py", line 1307, in run_query
        metadata=metadata,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
        return wrapped_func(*args, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
        on_error=on_error,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
        return target()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 166, in error_remapped_callable
        raise exceptions.from_grpc_error(exc) from exc
    google.api_core.exceptions.PermissionDenied: 403 Missing or insufficient permissions.

I opened the `main.py` file and checked line 17, here is the code:

    collection = db.collection(u"collection")
    docs = collection.stream()
    
    for doc in docs: # File "main.py", line 17
        print(f'{doc.id} => {doc.to_dict()}')

When I resolve the error using [this answer][1] it shows the following:

    Error: There are no available Google Cloud projects to add Firebase services.

When I resolve the error using [this answer][2] it shows the following and the result is different:

         ######## #### ########  ######## ########     ###     ######  ########
         ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
         ######    ##  ########  ######   ########  #########  ######  ######
         ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
         ##       #### ##     ## ######## ########  ##     ##  ######  ########
    
    You're about to initialize a Firebase project in this directory:
    
      /Users/name/development/projects/python/project-id
    
    ? Which Firebase features do you want to set up for this directory? Press Space to select features, then Enter to confirm your choices. (Press <s
    pace> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
    ❯◯ Realtime Database: Configure a security rules file for Realtime Database and (optionally) provision default instance
     ◯ Firestore: Configure security rules and indexes files for Firestore
     ◯ Functions: Configure a Cloud Functions directory and its files
     ◯ Hosting: Configure files for Firebase Hosting and (optionally) set up GitHub Action deploys
     ◯ Hosting: Set up GitHub Action deploys
     ◯ Storage: Configure a security rules file for Cloud Storage
     ◯ Emulators: Set up local emulators for Firebase products

[![Get different results][3]][3]

I suspect the missing permissions mean that the Google Cloud Firestore security rules write blocks read and write. The following are the Google Cloud Firestore security rules:

    rules_version = '2';
    service cloud.firestore {
      match /databases/{database}/documents {
        match /{document=**} {
          allow read, write: if false;
        }
      }
    }

If I'm correct, the code above will block reading and writing. When I want to edit the code it says this is a read only editor. Above the code is the following:

[![This picture is what is above the code][4]][4]

When I click the "[Learn more][5]" button, it takes me to an article and I use the `firebase init firestore` command. However, it asks me to choose a Firebase project, and the project I'm using is not a Firebase project, but a Google Cloud project. Then I refer to this link and do what it says.

When I do 1b (Select your existing Google Cloud project from the dropdown menu, then click Continue.) in the create Firebase project page, there is no dropdown to select an existing Google Cloud project.

Why does this problem occur here? Is this a bug of the Google team or my mistake or something? Or changing Google Cloud Firestore security rules is not a solution? If anyone could help me, I would appreciate it. Thank you in advance!

  [1]: https://stackoverflow.com/a/72522180/16124033
  [2]: https://stackoverflow.com/a/72522183/16124033
  [3]: https://i.stack.imgur.com/9bnBB.png
  [4]: https://i.stack.imgur.com/jUUWj.png
  [5]: https://cloud.google.com/firestore/docs/security/get-started?&_ga=2.79259356.-958014234.1664260918&_gac=1.215300453.1666309908.Cj0KCQjw48OaBhDWARIsAMd966B4TgFacIwEeTfSnNgLq_zyprheNCrJCa_B0QSCMgv3wOW4f_Ptd-YaAriFEALw_wcB#use_the_firebase_cli

**Comment by dandhlee** [comment]
Hi there. If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. We don't provide general support for Google Cloud.

Did you run into an issue while using Google Cloud for any of the files within this repository? If not, we unfortunately can't help you. Let me know if you were trying to run a sample file in this repository, then I can try and point you (or get someone else to point you) in the right direction.

**Comment by dandhlee** [comment]
Closing due to inactivity. Please re-open the issue and help let us know, or feel free to open a new issue.
