### ISSUE TITLE
Video Intelligence FACE_DETECTION and SAFE_SEARCH_DETECTION Problem

### ISSUE THREAD

**Issue by nesatArcelik** [GoogleCloudPlatform/python-docs-samples#967]
I try to use "python-docs-samples/video/cloud-client/analyze/" sample without any change. LABEL_DETECTION and SHOT_CHANGE_DETECTION examples working well. However I'm having problems with when I try to use FACE_DETECTION or SAFE_SEARCH_DETECTION.

I call using:
python analyze/analyze.py labels gs://cloudmleap/video/next/animals.mp4
python analyze/analyze.py shots gs://cloudmleap/video/next/animals.mp4
python analyze/analyze.py safe_search gs://cloudmleap/video/next/animals.mp4
python analyze/analyze.py faces gs://cloudmleap/video/next/animals.mp4

First two examples work well as I mentioned before!

I got the following errors when I try last command:

Traceback (most recent call last):
  File "analyze/analyze.py", line 229, in <module>
    analyze_faces(args.path)
  File "analyze/analyze.py", line 77, in analyze_faces
    operation = video_client.annotate_video(path, features)
  File "/home/myusername/python-docs-samples/video/cloud-client/env/local/lib/python2.7/site-packages/google/cloud/gapic/videointelligence/v1beta1/video_intelligence_service_client.py", line 237, in annotate_video
    self._annotate_video(request, options), self.operations_client,
  File "/home/myusername/python-docs-samples/video/cloud-client/env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 428, in inner
    return api_caller(api_call, this_settings, request)
  File "/home/myusername/python-docs-samples/video/cloud-client/env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 416, in base_caller
    return api_call(*args)
  File "/home/myusername/python-docs-samples/video/cloud-client/env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/home/myusername/python-docs-samples/video/cloud-client/env/local/lib/python2.7/site-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
google.gax.errors.RetryError: GaxError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Request contains an invalid argument.)>)

**Comment by jonparrott** [comment]
@gguuss any ideas?

@lukesneeringer is there any way we can improve that error message?

**Comment by gguuss** [comment]
@nesatArcelik It appears you don't have access to the `faces` and `safe_search` features as these are still private.

**Comment by nesatArcelik** [comment]
I filled the form at https://docs.google.com/a/google.com/forms/d/e/1FAIpQLSc87dTWnrCtWRjNvg0430u-dhIH-98Vwnage-zD9Z4a7DHcBQ/viewform almost one month ago. Is there a step I missed?

**Comment by gguuss** [comment]
You will not have access to the EAP features (face detection and safe search detection) until you have been approved into the program and have followed any instructions mailed to you upon acceptance.

**Comment by nesatArcelik** [comment]
Thank you, is there a way to check status of my application? BTW I have two applications and one of them is personal application which I am planning to use for my master thesis.

**Comment by gguuss** [comment]
@nesatArcelik I'm not sure of a good way to check / expedite access to our EAP features. It's been a while since I checked in with you, has your access gone through?

**Comment by nesatArcelik** [comment]
No, I've tried right now and I received exactly same error

**Comment by engelke** [comment]
The APIs have been updated and open to wider use since this report.
