### ISSUE TITLE
contentwarehouse/snippets:python3.7 build test failed 

### ISSUE THREAD

**Issue by dmoonat** [GoogleCloudPlatform/python-docs-samples#9821]
## In which file did you encounter the issue?
contentwarehouse/snippets/set_acl_sample_test.py
contentwarehouse/snippets/fetch_acl_sample_test.py

## Did you change the file? If so, how?
NA

## Describe the issue
The python 3.7 build test is failing, with google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument exception.

Traceback:
___________________________ test_set_document_acl _____________________________
Traceback (most recent call last):
  File "/workspace/contentwarehouse/snippets/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/workspace/contentwarehouse/snippets/.nox/py-3-7/lib/python3.7/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/workspace/contentwarehouse/snippets/.nox/py-3-7/lib/python3.7/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Request contains an invalid argument."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.114.95:443 {created_time:"2023-04-24T20:10:40.608756432+00:00", grpc_status:3, grpc_message:"Request contains an invalid argument."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/contentwarehouse/snippets/set_acl_sample_test.py", line 63, in test_set_document_acl
    document_id=document_id,
  File "/workspace/contentwarehouse/snippets/set_acl_sample.py", line 73, in set_acl
    response = client.set_acl(request=request)
  File "/workspace/contentwarehouse/snippets/.nox/py-3-7/lib/python3.7/site-packages/google/cloud/contentwarehouse_v1/services/document_service/client.py", line 1402, in set_acl
    metadata=metadata,
  File "/workspace/contentwarehouse/snippets/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/workspace/contentwarehouse/snippets/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/workspace/contentwarehouse/snippets/.nox/py-3-7/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.
--- generated xml file: /workspace/contentwarehouse/snippets/sponge_log.xml ----
=========================== short test summary info ============================
FAILED set_acl_sample_test.py::test_set_document_acl - google.api_core.except...
========================= 1 failed, 8 passed in 13.19s =========================
nox > Command pytest --junitxml=sponge_log.xml failed with exit code 1
nox > Session py-3.7 failed.
PWD: /workspace/contentwarehouse/snippets

Build logs: https://source.cloud.google.com/results/invocations/ae8a58c7-dd09-4219-9189-2ddd448546a2/targets/cloud-devrel%2Fpython-docs-samples%2Fpython3.7%2Fpresubmit/log

**Comment by kweinmeister** [comment]
No longer seeing this issue. Please reopen if it still exists.
