### ISSUE TITLE
Unable to install google-cloud-videointelligence in python3.4 virtualenv

### ISSUE THREAD

**Issue by odoric27** [GoogleCloudPlatform/python-docs-samples#989]
i've been working through the samples under video/ using python2.7 mostly without issue, but i'm unable to even get virtualenv running with python 3.4.

after creating and activating the 3.4 env i try to `pip install -r requirements.txt` to install `google-cloud-videointelligence==0.25.0`, but the installation also crashes after running setup.py for google-gax

```
Installing collected packages: google-cloud-videointelligence, six, google-gax, googleapis-common-protos, dill, future, grpcio, google-auth, ply, protobuf, requests, pyasn1, pyasn1-modules, rsa, cachetools, certifi, chardet, idna, urllib3
  Running setup.py install for google-gax
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extension import Extension
      File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/setuptools/dist.py", line 16, in <module>
        import pkg_resources
      File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 2736, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 698, in subscribe
        callback(dist)
      File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 2736, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 2274, in activate
        list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))
      File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 1870, in declare_namespace
        path = sys.modules[parent].__path__
    KeyError: 'google.cloud'
    Complete output from command /src/mono/video_content_search/project/env3/bin/python3 -c "import setuptools, tokenize;__file__='/src/mono/video_content_search/project/env3/build/google-gax/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pza0osnp-record/install-record.txt --single-version-externally-managed --compile --install-headers /src/mono/video_content_search/project/env3/include/site/python3.4:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/setuptools/__init__.py", line 11, in <module>

    from setuptools.extension import Extension

  File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/setuptools/extension.py", line 5, in <module>

    from setuptools.dist import _get_unpatched

  File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/setuptools/dist.py", line 16, in <module>

    import pkg_resources

  File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 2736, in <module>

    add_activation_listener(lambda dist: dist.activate())

  File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 698, in subscribe

    callback(dist)

  File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 2736, in <lambda>

    add_activation_listener(lambda dist: dist.activate())

  File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 2274, in activate

    list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))

  File "/src/mono/video_content_search/project/env3/lib/python3.4/site-packages/pkg_resources.py", line 1870, in declare_namespace

    path = sys.modules[parent].__path__

KeyError: 'google.cloud'

----------------------------------------
Cleaning up...
Command /src/mono/video_content_search/project/env3/bin/python3 -c "import setuptools, tokenize;__file__='/src/mono/video_content_search/project/env3/build/google-gax/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pza0osnp-record/install-record.txt --single-version-externally-managed --compile --install-headers /src/mono/video_content_search/project/env3/include/site/python3.4 failed with error code 1 in /src/mono/video_content_search/project/env3/build/google-gax
Storing debug log for failure in /root/.pip/pip.log
```

Any help would be appreciated!

**Comment by jonparrott** [comment]
/cc @lukesneeringer

I think you need to make sure you have the latest pip and setuptools, which you can get via `pip install --upgrade setuptools pip`. 

Also, our libraries are starting to target 3.5+.

(closing, but let me know if that doesn't solve your issue)

**Comment by odoric27** [comment]
thanks @jonparrott ! that did the trick. appreciate the heads up re: moving to 3.5+

**Comment by jonparrott** [comment]
Happy to help. :)

**Comment by madhusrhd** [comment]
pip says everything up to date but fails to install google components.

Requirement already up-to-date: setuptools in .\lib\site-packages
Requirement already up-to-date: pip in .\lib\site-packages
